// Auto-generated by scripts/split-requirement-index.mjs
// DO NOT EDIT MANUALLY — re-run the script to regenerate

export interface ResourceEntry {
  uri: string;
  type: string;
  size: number;
  description: string;
  crossRefs: string[];
}

export const resources: Record<string, ResourceEntry> = {
  "requirement-epic-req-aut-auth": {
    "uri": "resource://requirement-index/requirement-epic-req-aut-auth.json",
    "type": "json",
    "size": 6738,
    "description": "Requirements for epic \"Authentication System\": 16 items (2 features, 13 stories)",
    "crossRefs": []
  },
  "requirement-epic-req-aut-dashboard": {
    "uri": "resource://requirement-index/requirement-epic-req-aut-dashboard.json",
    "type": "json",
    "size": 3956,
    "description": "Requirements for epic \"Dashboard\": 10 items (2 features, 7 stories)",
    "crossRefs": []
  },
  "requirement-epic-req-aut-user-mgmt": {
    "uri": "resource://requirement-index/requirement-epic-req-aut-user-mgmt.json",
    "type": "json",
    "size": 23506,
    "description": "Requirements for epic \"User Management\": 54 items (8 features, 45 stories)",
    "crossRefs": []
  },
  "requirement-epic-req-aut-reports": {
    "uri": "resource://requirement-index/requirement-epic-req-aut-reports.json",
    "type": "json",
    "size": 5102,
    "description": "Requirements for epic \"Reports & Analytics\": 13 items (4 features, 8 stories)",
    "crossRefs": []
  },
  "requirement-epic-req-aut-fault": {
    "uri": "resource://requirement-index/requirement-epic-req-aut-fault.json",
    "type": "json",
    "size": 3845,
    "description": "Requirements for epic \"Fault Injection & Testing Utilities\": 10 items (3 features, 6 stories)",
    "crossRefs": []
  }
} as const;

export function getResourceKeys(): string[] {
  return Object.keys(resources);
}

export function getResourceByKey(key: string): ResourceEntry | undefined {
  return resources[key];
}
