export const queryKeys = {
  projects: ['projects'] as const,
  suites: ['suites'] as const,
  headers: ['headers'] as const,
  bodies: ['bodies'] as const,
  endpoints: ['endpoints'] as const,
  settings: ['settings'] as const,
  environments: ['environments'] as const,
  reports: ['reports'] as const,
  dynamicVariables: (projectId: string) => ['dynamic-variables', projectId] as const,
  agents: ['agents'] as const,
  requirements: ['requirements'] as const,
  businessFlows: ['business-flows'] as const,
  queue: ['queue'] as const,
  pipeline: {
    runs: (projectId: string) => ['pipeline', 'runs', projectId] as const,
    checkpoint: (runId: string) => ['pipeline', 'checkpoint', runId] as const,
    logs: (runId: string) => ['pipeline', 'logs', runId] as const,
  },
  nlCases: (projectId: string) => ['nl-cases', projectId] as const,
};
