export const queryKeys = {
  projects: ['projects'] as const,
  suites: ['suites'] as const,
  headers: ['headers'] as const,
  bodies: ['bodies'] as const,
  endpoints: ['endpoints'] as const,
  settings: ['settings'] as const,
  environments: ['environments'] as const,
  reports: ['reports'] as const,
  dynamicVariables: (projectId: string) => ['dynamic-variables', projectId] as const,
  agents: ['agents'] as const,
  requirements: ['requirements'] as const,
  queue: ['queue'] as const,
  testGen: {
    runs: (projectId: string) => ['test-gen', 'runs', projectId] as const,
    checkpoint: (runId: string) => ['test-gen', 'checkpoint', runId] as const,
    logs: (runId: string) => ['test-gen', 'logs', runId] as const,
  },
  nlCases: (projectId: string) => ['nl-cases', projectId] as const,
  providerConfigs: ['provider-configs'] as const,
  aiRecorder: {
    runs: (projectId: string) => ['ai-recorder', 'runs', projectId] as const,
    run: (runId: string) => ['ai-recorder', 'run', runId] as const,
  },
};
