import { Log } from '../../shared/services/logger';
import type { Requirement } from '../../shared/contracts/index.ts';
import { requirementRepo } from './repository.ts';

const AUT_PROJECT_ID = 'p-aut-demo';

const requirements: Requirement[] = [
  // ═══════════════════════════════════════════════════════════════
  // Epic 1: Authentication System (humanId: AUTH)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'req-aut-auth',
    projectId: AUT_PROJECT_ID,
    parentId: null,
    title: 'Authentication System',
    description: 'Secure login and session management for the AUT application, covering the login UI, input validation, and the end-to-end authentication session flow.',
    level: 'epic',
    humanId: 'AUTH',
    type: 'functional',
    status: 'APPROVED',
    position: 0,
  },

  // ── Story 1: Login Page UI ──────────────────────────────────────
  {
    id: 'req-aut-auth-login-ui',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth',
    title: 'Login Page UI',
    description: 'The login page renders a username/password form with a password visibility toggle, a "Remember me" checkbox, and a "Forgot password" link.',
    level: 'story',
    type: 'functional',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-auth-login-ui-form',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-login-ui',
    title: 'Login form display',
    description: 'Given the user navigates to the login page\nWhen the page finishes loading\nThen the login form is displayed with a username input, a password input, and a submit button',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-auth-login-ui-password-toggle',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-login-ui',
    title: 'Password visibility toggle',
    description: 'Given the user is on the login page\nWhen the user clicks the password visibility toggle\nThen the password field changes from masked to plain text',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-auth-login-ui-remember',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-login-ui',
    title: 'Remember me checkbox',
    description: 'Given the user is on the login page\nWhen the user views the login form\nThen a "Remember me" checkbox is displayed below the password field',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 2,
  },
  {
    id: 'req-aut-auth-login-ui-forgot',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-login-ui',
    title: 'Forgot password link',
    description: 'Given the user is on the login page\nWhen the user views the login form\nThen a "Forgot password?" link is displayed below the password field',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 3,
  },

  // ── Story 2: Login Validation ──────────────────────────────────
  {
    id: 'req-aut-auth-login-validation',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth',
    title: 'Login Validation',
    description: 'The login form validates user input and surfaces clear error messages for empty fields and invalid credentials.',
    level: 'story',
    type: 'functional',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-auth-login-validation-empty',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-login-validation',
    title: 'Empty field validation',
    description: 'Given the user is on the login page\nWhen the user submits the form with an empty username or password\nThen the error message "Please fill in all required fields" is displayed',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-auth-login-validation-invalid',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-login-validation',
    title: 'Invalid credentials error',
    description: 'Given the user is on the login page\nWhen the user submits the form with invalid credentials\nThen an error message is displayed indicating the credentials are invalid',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 1,
  },

  // ═══════════════════════════════════════════════════════════════
  // Epic 2: Dashboard & Home (humanId: DASH)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'req-aut-dashboard',
    projectId: AUT_PROJECT_ID,
    parentId: null,
    title: 'Dashboard & Home',
    description: 'The home dashboard provides an overview of system status, user statistics, and quick navigation links to other sections of the application.',
    level: 'epic',
    humanId: 'DASH',
    type: 'functional',
    status: 'APPROVED',
    position: 1,
  },

  // ── Story 1: Dashboard Layout ──────────────────────────────────
  {
    id: 'req-aut-dashboard-layout',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-dashboard',
    title: 'Dashboard Layout',
    description: 'The dashboard renders a personalized welcome banner, quick action links, and a row of stat cards summarizing key system metrics.',
    level: 'story',
    type: 'functional',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-dashboard-layout-welcome',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-dashboard-layout',
    title: 'Welcome banner',
    description: 'Given the user is logged in and on the dashboard\nWhen the dashboard loads\nThen a welcome banner is displayed with the text "Welcome back, Admin!"',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-dashboard-layout-quick-actions',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-dashboard-layout',
    title: 'Quick action links',
    description: 'Given the user is on the dashboard\nWhen the user views the quick action section\nThen "Manage Users" and "View Reports" links are displayed',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-dashboard-layout-stat-cards',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-dashboard-layout',
    title: 'Stat cards layout',
    description: 'Given the user is on the dashboard\nWhen the dashboard loads\nThen three stat cards are displayed for Total Users, Active Sessions, and System Status',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 2,
  },

  // ── Story 2: Dashboard Stats ───────────────────────────────────
  {
    id: 'req-aut-dashboard-stats',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-dashboard',
    title: 'Dashboard Stats',
    description: 'The dashboard stat cards display real-time values for total users, active sessions, and the system status indicator, sourced from the dashboard stats API.',
    level: 'story',
    type: 'functional',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-dashboard-stats-total-users',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-dashboard-stats',
    title: 'Total users count',
    description: 'Given the dashboard statistics are loaded\nWhen the user views the Total Users stat card\nThen the total number of users is displayed',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-dashboard-stats-active-sessions',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-dashboard-stats',
    title: 'Active sessions count',
    description: 'Given the dashboard statistics are loaded\nWhen the user views the Active Sessions stat card\nThen the number of active sessions is displayed',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-dashboard-stats-system-status',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-dashboard-stats',
    title: 'System status indicator',
    description: 'Given the dashboard statistics are loaded\nWhen the user views the System Status stat card\nThen the system status is displayed indicating the system is online',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 2,
  },

  // ═══════════════════════════════════════════════════════════════
  // Epic 3: User Management (humanId: UM)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'req-aut-um',
    projectId: AUT_PROJECT_ID,
    parentId: null,
    title: 'User Management',
    description: 'Comprehensive user management covering list and filtering, sorting and pagination, simple and advanced creation forms, view and edit, delete, batch operations, the action drawer, and the end-to-end user management flow.',
    level: 'epic',
    humanId: 'UM',
    type: 'functional',
    status: 'APPROVED',
    position: 2,
  },

  // ── Story 1: User List & Filtering ─────────────────────────────
  {
    id: 'req-aut-um-list',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um',
    title: 'User List & Filtering',
    description: 'The user list displays all users in a table and supports filtering by name search, role dropdown, and status dropdown with Apply and Reset controls.',
    level: 'story',
    type: 'functional',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-um-list-table',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-list',
    title: 'Table display',
    description: 'Given the user is on the User Management page\nWhen the user list loads\nThen a table is displayed with columns for checkbox, Name, Email, Role, Status, Created At, Last Modified, and Actions',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-um-list-search-name',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-list',
    title: 'Name search',
    description: 'Given the user is on the User Management page\nWhen the user enters text in the name search input and clicks Apply\nThen the table is filtered to show only users whose names match the search text',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-um-list-filter-role',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-list',
    title: 'Role filter',
    description: 'Given the user is on the User Management page\nWhen the user selects a role from the Role dropdown and clicks Apply\nThen the table is filtered to show only users with the selected role',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 2,
  },
  {
    id: 'req-aut-um-list-filter-status',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-list',
    title: 'Status filter',
    description: 'Given the user is on the User Management page\nWhen the user selects a status from the Status dropdown and clicks Apply\nThen the table is filtered to show only users with the selected status',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 3,
  },
  {
    id: 'req-aut-um-list-apply-reset',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-list',
    title: 'Apply and Reset',
    description: 'Given the user has applied filters on the User Management page\nWhen the user clicks the Reset button\nThen all filters are cleared and the table shows all users',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 4,
  },

  // ── Story 2: User Table Sorting & Pagination ───────────────────
  {
    id: 'req-aut-um-sorting-pagination',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um',
    title: 'User Table Sorting & Pagination',
    description: 'The user table supports column sorting and pagination with page navigation and record count information.',
    level: 'story',
    type: 'functional',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-um-sorting-pagination-sort',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-sorting-pagination',
    title: 'Column sort',
    description: 'Given the user is viewing the user table\nWhen the user clicks a sortable column header\nThen the table is sorted by that column in ascending or descending order with a visual indicator',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-um-sorting-pagination-nav',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-sorting-pagination',
    title: 'Pagination navigation',
    description: 'Given the user table contains more users than fit on one page\nWhen the user clicks a page number or prev/next button\nThen the table displays the corresponding page of users',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-um-sorting-pagination-info',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-sorting-pagination',
    title: 'Page info',
    description: 'Given the user is viewing a paginated user table\nWhen the user views the pagination section\nThen the current page and total record count information is displayed',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 2,
  },

  // ── Story 3: User Creation - Simple Form ───────────────────────
  {
    id: 'req-aut-um-create-simple',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um',
    title: 'User Creation - Simple Form',
    description: 'A Quick Add modal provides a minimal form for rapidly creating a new user with name, email, role, and status fields.',
    level: 'story',
    type: 'functional',
    status: 'APPROVED',
    position: 2,
  },
  {
    id: 'req-aut-um-create-simple-modal',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-create-simple',
    title: 'Modal opens',
    description: 'Given the user is on the User Management page\nWhen the user clicks the Quick Add button\nThen a modal opens with fields for name, email, role, and status',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-um-create-simple-required',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-create-simple',
    title: 'Required fields',
    description: 'Given the Quick Add modal is open\nWhen the user submits the form without filling in the required fields\nThen validation errors are displayed for the missing required fields',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-um-create-simple-save',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-create-simple',
    title: 'Save success',
    description: 'Given the Quick Add modal is open with valid data\nWhen the user clicks Save\nThen the user is created, a success toast is displayed, and the table is refreshed',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 2,
  },

  // ── Story 4: User Creation - Advanced Form ─────────────────────
  {
    id: 'req-aut-um-create-advanced',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um',
    title: 'User Creation - Advanced Form',
    description: 'An Advanced Add modal provides a comprehensive form with four sections (Personal Details, Job Details, Security & Settings, Profile Picture) including a cascading department selector, permissions checkboxes, access level slider, and 2FA toggle.',
    level: 'story',
    type: 'functional',
    status: 'APPROVED',
    position: 3,
  },
  {
    id: 'req-aut-um-create-advanced-sections',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-create-advanced',
    title: 'Form sections',
    description: 'Given the user is on the User Management page\nWhen the user clicks the Advanced Add button\nThen a modal opens with four sections: Personal Details, Job Details, Security & Settings, and Profile Picture',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-um-create-advanced-cascader',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-create-advanced',
    title: 'Cascader',
    description: 'Given the Advanced Add modal is open\nWhen the user interacts with the department cascader\nThen a three-level cascading selector is displayed (Development → Frontend → React)',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-um-create-advanced-permissions',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-create-advanced',
    title: 'Permissions',
    description: 'Given the Advanced Add modal is open\nWhen the user views the Security & Settings section\nThen permission checkboxes are displayed for view_reports, manage_users, billing_access, and api_access',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 2,
  },
  {
    id: 'req-aut-um-create-advanced-2fa',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-create-advanced',
    title: '2FA toggle',
    description: 'Given the Advanced Add modal is open\nWhen the user views the Security & Settings section\nThen a 2FA toggle switch is displayed',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 3,
  },
  {
    id: 'req-aut-um-create-advanced-slider',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-create-advanced',
    title: 'Access slider',
    description: 'Given the Advanced Add modal is open\nWhen the user views the Security & Settings section\nThen an access level slider ranging from 1 to 5 is displayed',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 4,
  },
  {
    id: 'req-aut-um-create-advanced-save',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-create-advanced',
    title: 'Save',
    description: 'Given the Advanced Add modal is open with valid data\nWhen the user clicks Save\nThen the user is created and a success toast is displayed',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 5,
  },

  // ── Story 5: User View & Edit ──────────────────────────────────
  {
    id: 'req-aut-um-view-edit',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um',
    title: 'User View & Edit',
    description: 'Users can be viewed in a read-only details modal and edited through a form pre-filled with the selected user\'s current data.',
    level: 'story',
    type: 'functional',
    status: 'APPROVED',
    position: 4,
  },
  {
    id: 'req-aut-um-view-edit-view',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-view-edit',
    title: 'View modal',
    description: 'Given the user is viewing the user table\nWhen the user clicks the View action (eye icon) on a row\nThen a read-only modal opens displaying all user fields in five sections',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-um-view-edit-edit',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-view-edit',
    title: 'Edit pre-fill',
    description: 'Given the user is viewing the user table\nWhen the user clicks the Edit action (pencil) on a row\nThen the edit form opens with all fields pre-filled with the user\'s current data',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-um-view-edit-save',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-view-edit',
    title: 'Save update',
    description: 'Given the edit form is open with modified data\nWhen the user clicks Save\nThen the user record is updated and a success toast is displayed',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 2,
  },

  // ── Story 6: User Delete ───────────────────────────────────────
  {
    id: 'req-aut-um-delete',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um',
    title: 'User Delete',
    description: 'Deleting a user requires confirmation, shows a success toast, and refreshes the table so the deleted user no longer appears.',
    level: 'story',
    type: 'functional',
    status: 'APPROVED',
    position: 5,
  },
  {
    id: 'req-aut-um-delete-confirm',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-delete',
    title: 'Confirm dialog',
    description: 'Given the user is viewing the user table\nWhen the user clicks the Delete action (trash) on a row\nThen a confirmation dialog is displayed asking the user to confirm the deletion',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-um-delete-success',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-delete',
    title: 'Delete success',
    description: 'Given the delete confirmation dialog is displayed\nWhen the user confirms the deletion\nThen the user is deleted and a success toast is displayed',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-um-delete-refresh',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-delete',
    title: 'Table refresh',
    description: 'Given a user has been successfully deleted\nWhen the deletion completes\nThen the user table is refreshed and the deleted user no longer appears in the list',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 2,
  },

  // ── Story 7: Batch Operations ──────────────────────────────────
  {
    id: 'req-aut-um-batch',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um',
    title: 'Batch Operations',
    description: 'Multiple users can be selected for batch operations including activate all, deactivate all, batch delete, with a mixed-status warning that disables status update buttons.',
    level: 'story',
    type: 'functional',
    status: 'APPROVED',
    position: 6,
  },
  {
    id: 'req-aut-um-batch-select-all',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-batch',
    title: 'Select all',
    description: 'Given the user is viewing the user table\nWhen the user clicks the header checkbox\nThen all visible users on the current page are selected',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-um-batch-activate',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-batch',
    title: 'Batch activate',
    description: 'Given multiple users are selected\nWhen the user clicks the Activate All button\nThen all selected users have their status set to active',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-um-batch-deactivate',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-batch',
    title: 'Batch deactivate',
    description: 'Given multiple users are selected\nWhen the user clicks the Deactivate All button\nThen all selected users have their status set to inactive',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 2,
  },
  {
    id: 'req-aut-um-batch-delete',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-batch',
    title: 'Batch delete',
    description: 'Given multiple users are selected\nWhen the user clicks the Delete Selected button and confirms\nThen all selected users are deleted',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 3,
  },
  {
    id: 'req-aut-um-batch-mixed',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-batch',
    title: 'Mixed status warning',
    description: 'Given users with mixed active and inactive statuses are selected\nWhen the user views the batch operation bar\nThen a warning badge is displayed and the Activate All and Deactivate All buttons are disabled',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 4,
  },

  // ── Story 8: User Action Drawer ────────────────────────────────
  {
    id: 'req-aut-um-drawer',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um',
    title: 'User Action Drawer',
    description: 'A slide-in action drawer exposes per-user actions: send password reset, export user data as JSON, and suspend the account by setting its status to inactive.',
    level: 'story',
    type: 'functional',
    status: 'APPROVED',
    position: 7,
  },
  {
    id: 'req-aut-um-drawer-reset',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-drawer',
    title: 'Reset password',
    description: 'Given the user has opened the action drawer for a user\nWhen the user clicks Send Password Reset\nThen a password reset is triggered for the selected user',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-um-drawer-export',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-drawer',
    title: 'Export data',
    description: 'Given the user has opened the action drawer for a user\nWhen the user clicks Export User Data\nThen the user\'s data is downloaded as a JSON file',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-um-drawer-suspend',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-drawer',
    title: 'Suspend account',
    description: 'Given the user has opened the action drawer for a user\nWhen the user clicks Suspend Account\nThen the selected user\'s status is set to inactive',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 2,
  },

  // ═══════════════════════════════════════════════════════════════
  // Epic 4: Reports & Analytics (humanId: RPT)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'req-aut-reports',
    projectId: AUT_PROJECT_ID,
    parentId: null,
    title: 'Reports & Analytics',
    description: 'Visual data reports including summary cards, a pie chart for user role distribution, a bar chart for users by department, and a loading state during data fetch.',
    level: 'epic',
    humanId: 'RPT',
    type: 'functional',
    status: 'APPROVED',
    position: 3,
  },

  // ── Story 1: Reports Dashboard ─────────────────────────────────
  {
    id: 'req-aut-reports-dashboard',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-reports',
    title: 'Reports Dashboard',
    description: 'The reports page renders four summary cards, a role distribution pie chart, a department bar chart, and a loading spinner while data is being fetched.',
    level: 'story',
    type: 'functional',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-reports-dashboard-cards',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-reports-dashboard',
    title: 'Summary cards',
    description: 'Given the user is on the Reports page\nWhen the reports data loads\nThen four summary cards are displayed showing Total Users, Active Accounts, Admins count, and Engagement Rate',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-reports-dashboard-pie',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-reports-dashboard',
    title: 'Pie chart',
    description: 'Given the user is on the Reports page\nWhen the reports data loads\nThen a pie chart is displayed showing User Role Distribution across admin, editor, and viewer segments',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-reports-dashboard-bar',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-reports-dashboard',
    title: 'Bar chart',
    description: 'Given the user is on the Reports page\nWhen the reports data loads\nThen a bar chart is displayed showing Users by Department',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 2,
  },
  {
    id: 'req-aut-reports-dashboard-loading',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-reports-dashboard',
    title: 'Loading state',
    description: 'Given the user navigates to the Reports page\nWhen the reports data is being fetched\nThen a loading spinner is displayed until the data is loaded',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 3,
  },

  // ═══════════════════════════════════════════════════════════════
  // Epic 5: Fault Injection (humanId: FLT)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'req-aut-fault',
    projectId: AUT_PROJECT_ID,
    parentId: null,
    title: 'Fault Injection',
    description: 'Endpoints designed for testing error handling, timeouts, and content type variations in automated tests, including a 5-second delay, a random 500 error, and an XML content type response.',
    level: 'epic',
    humanId: 'FLT',
    type: 'functional',
    status: 'APPROVED',
    position: 4,
  },

  // ── Story 1: Fault Injection Endpoints ─────────────────────────
  {
    id: 'req-aut-fault-endpoints',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-fault',
    title: 'Fault Injection Endpoints',
    description: 'Three fault injection endpoints simulate a timeout delay, a random 500 error, and an XML content type response for testing client error handling.',
    level: 'story',
    type: 'functional',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-fault-endpoints-timeout',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-fault-endpoints',
    title: 'Timeout delay',
    description: 'Given the fault injection API is available\nWhen a request is made to GET /aut-api/fault/timeout\nThen the response is delayed by 5 seconds before returning',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-fault-endpoints-500',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-fault-endpoints',
    title: 'Random 500',
    description: 'Given the fault injection API is available\nWhen a request is made to GET /aut-api/fault/simulate-500\nThen the endpoint returns a 500 error with approximately 50% probability',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-fault-endpoints-xml',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-fault-endpoints',
    title: 'XML content',
    description: 'Given the fault injection API is available\nWhen a request is made to GET /aut-api/fault/xml-content\nThen the response is returned with an XML content type',
    level: 'ac',
    flowType: 'atomic',
    type: 'functional',
    status: 'APPROVED',
    position: 2,
  },

  // ═══════════════════════════════════════════════════════════════
  // Flow Stories (BDD Features) — placed after all functional stories
  // so relatedRequirementIds references resolve at save time.
  // Each flow story's parentId links it to its owning epic.
  // ═══════════════════════════════════════════════════════════════

  // ── Flow: Authentication Session (under Epic 1: AUTH) ──────────
  {
    id: 'req-aut-auth-session',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth',
    title: 'Authentication Session',
    description: 'BDD Feature covering the authentication session lifecycle: a happy-path login that stores a token and redirects to the dashboard, plus exception scenarios for invalid credentials and empty fields.',
    level: 'story',
    isFlow: true,
    type: 'functional',
    status: 'APPROVED',
    position: 2,
  },
  {
    id: 'req-aut-auth-session-happy',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-session',
    title: 'Happy path: valid credentials authenticate and redirect to dashboard',
    description: 'Given the user is on the login page with valid credentials\nWhen the user enters the credentials and submits the form\nThen the authentication API returns a token, the token is stored in localStorage, and the user is redirected to the dashboard',
    level: 'ac',
    flowType: 'flow',
    relatedRequirementIds: ['req-aut-auth-login-ui', 'req-aut-auth-login-validation'],
    type: 'functional',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-auth-session-invalid',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-session',
    title: 'Exception: invalid credentials show error and allow retry',
    description: 'Given the user is on the login page with invalid credentials\nWhen the user enters the credentials and submits the form\nThen an error message is shown and the user can retry the login',
    level: 'ac',
    flowType: 'flow',
    relatedRequirementIds: ['req-aut-auth-login-validation', 'req-aut-auth-login-ui'],
    type: 'functional',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-auth-session-empty',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-session',
    title: 'Exception: empty fields block form submission with validation error',
    description: 'Given the user is on the login page\nWhen the user submits the form without filling in all required fields\nThen a validation error is shown and the form is not submitted',
    level: 'ac',
    flowType: 'flow',
    relatedRequirementIds: ['req-aut-auth-login-validation', 'req-aut-auth-login-ui'],
    type: 'functional',
    status: 'APPROVED',
    position: 2,
  },

  // ── Flow: Login to Reports Journey (under Epic 1: AUTH) ────────
  {
    id: 'req-aut-auth-login-reports-flow',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth',
    title: 'Login to Reports Journey',
    description: 'BDD Feature tracing the cross-component happy path from login through the dashboard to the reports page, verifying that report data loads after authentication.',
    level: 'story',
    isFlow: true,
    type: 'functional',
    status: 'APPROVED',
    position: 3,
  },
  {
    id: 'req-aut-auth-login-reports-flow-happy',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-login-reports-flow',
    title: 'Happy path: login then navigate to reports and verify data loads',
    description: 'Given the user is on the login page\nWhen the user logs in and navigates to the reports page\nThen the reports data loads successfully and the summary cards and charts are displayed',
    level: 'ac',
    flowType: 'flow',
    relatedRequirementIds: ['req-aut-auth-login-ui', 'req-aut-dashboard-layout', 'req-aut-reports-dashboard'],
    type: 'functional',
    status: 'APPROVED',
    position: 0,
  },

  // ── Flow: User Management Flow (under Epic 3: UM) ──────────────
  {
    id: 'req-aut-um-flow',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um',
    title: 'User Management Flow',
    description: 'BDD Feature covering the end-to-end user management lifecycle: a happy-path create-view-edit cycle, an alternate batch-activate path, and an exception path where a deleted user is verified as removed from the list.',
    level: 'story',
    isFlow: true,
    type: 'functional',
    status: 'APPROVED',
    position: 8,
  },
  {
    id: 'req-aut-um-flow-happy',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-flow',
    title: 'Happy path: create user, view in list, edit, and verify changes',
    description: 'Given the admin is on the User Management page\nWhen the admin creates a new user, views it in the list, edits it, and saves the changes\nThen the user record is created, displayed in the list, and the edits are persisted',
    level: 'ac',
    flowType: 'flow',
    relatedRequirementIds: ['req-aut-um-create-simple', 'req-aut-um-list', 'req-aut-um-view-edit'],
    type: 'functional',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-um-flow-batch',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-flow',
    title: 'Alternate: select multiple users, batch activate, and verify status changed',
    description: 'Given the admin has selected multiple users on the User Management page\nWhen the admin performs a batch activate operation\nThen all selected users have their status changed to active',
    level: 'ac',
    flowType: 'flow',
    relatedRequirementIds: ['req-aut-um-batch'],
    type: 'functional',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-um-flow-delete',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-flow',
    title: 'Exception: delete user and verify removed from list',
    description: 'Given the admin is viewing the user list\nWhen the admin deletes a user\nThen the user is removed from the list',
    level: 'ac',
    flowType: 'flow',
    relatedRequirementIds: ['req-aut-um-delete', 'req-aut-um-list'],
    type: 'functional',
    status: 'APPROVED',
    position: 2,
  },
];

export function seedRequirements(): void {
  const existing = requirementRepo.listByProject(AUT_PROJECT_ID);
  if (existing.length > 0) {
    Log.for('seed').info(`AUT requirements already seeded (${existing.length} found), skipping.`);
    return;
  }
  for (const req of requirements) {
    requirementRepo.save(req);
  }
  Log.for('seed').info(`Seeded ${requirements.length} AUT requirements.`);
}
