import { Log } from '../../shared/services/logger';
import type { Requirement } from '../../shared/contracts/index.ts';
import { requirementRepo } from './repository.ts';

const AUT_PROJECT_ID = 'p-aut-demo';

const requirements: Requirement[] = [
  // ═══════════════════════════════════════════════════════════════
  // Epic 1: Authentication System
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'req-aut-auth',
    projectId: AUT_PROJECT_ID,
    parentId: null,
    title: 'Authentication System',
    description: 'Secure login and session management for the AUT application, covering the login UI (form fields, password toggle, remember me, forgot password), input validation (empty fields, invalid credentials, network errors), and the end-to-end authentication session flow (token storage, redirect, retry).',
    level: 'epic',
    status: 'APPROVED',
    position: 0,
  },

  // ── Story 1: Login Page UI ──────────────────────────────────────
  {
    id: 'req-aut-auth-login-ui',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth',
    title: 'Login Page UI',
    description: 'As a user\nI want to log in through a form with a username input (with User icon), a password input (with Lock icon and visibility toggle), a Remember me checkbox, a Forgot password link, and a Sign in submit button\nSo that I can securely access my account',
    level: 'story',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-auth-login-ui-form',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-login-ui',
    title: 'Login form display',
    description: 'Given the user navigates to /aut/login\nWhen the page finishes loading\nThen a login form is displayed with a heading "Sign in", a hint "Use admin / admin123 to login", a username input (id="username", placeholder "Enter username", with User icon), a password input (id="password", placeholder "Enter password", with Lock icon), and a submit button (id="submit-login-btn", text "Sign in")',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-auth-login-ui-password-toggle',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-login-ui',
    title: 'Password visibility toggle',
    description: 'Given the user is on the login page with the password field masked (type="password")\nWhen the user clicks the password visibility toggle button (id="toggle-password-btn")\nThen the password input type changes to "text" and the toggle icon changes from Eye to EyeOff\nAnd when clicked again, the password input type reverts to "password" and the icon changes back to Eye',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-auth-login-ui-remember',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-login-ui',
    title: 'Remember me checkbox',
    description: 'Given the user is on the login page\nWhen the user views the login form below the password field\nThen a "Remember me" checkbox (id="remember-me") is displayed in a row alongside the "Forgot password?" link',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 2,
  },
  {
    id: 'req-aut-auth-login-ui-forgot',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-login-ui',
    title: 'Forgot password link',
    description: 'Given the user is on the login page\nWhen the user views the login form below the password field\nThen a "Forgot password?" link is displayed on the right side of the Remember me row with blue text and hover effect',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 3,
  },
  {
    id: 'req-aut-auth-login-ui-submit-loading',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-login-ui',
    title: 'Submit button loading state',
    description: 'Given the user has submitted the login form with credentials\nWhen the authentication request is in progress\nThen the submit button text changes to "Signing in...", the button is disabled (cursor-not-allowed, bg-blue-400), and no duplicate submissions are accepted',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 4,
  },

  // ── Story 2: Login Validation ──────────────────────────────────
  {
    id: 'req-aut-auth-login-validation',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth',
    title: 'Login Validation',
    description: 'As a user\nI want the login form to validate my input before and after API submission, showing clear error messages for empty fields, invalid credentials, and network failures\nSo that I can correct mistakes and successfully sign in',
    level: 'story',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-auth-login-validation-empty',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-login-validation',
    title: 'Empty field validation',
    description: 'Given the user is on the login page\nWhen the user clicks Sign in with an empty username or empty password\nThen the error message "Please fill in all required fields." is displayed in a red error box (id="login-error") and no API request is sent',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-auth-login-validation-invalid',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-login-validation',
    title: 'Invalid credentials error',
    description: 'Given the user is on the login page\nWhen the user submits the form with credentials that do not match admin/admin123\nThen the POST /aut-api/auth/login returns 401 with { success: false, error: "Invalid credentials" } and the error message "Invalid credentials" is displayed in the red error box',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-auth-login-validation-network',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-login-validation',
    title: 'Network error handling',
    description: 'Given the user submits the login form\nWhen the fetch request to /aut-api/auth/login throws a network error (e.g., server unreachable)\nThen the error message "Network error occurred" is displayed in the red error box and the loading state is cleared',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 2,
  },
  {
    id: 'req-aut-auth-login-validation-success',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-login-validation',
    title: 'Successful login with token storage and redirect',
    description: 'Given the user enters username "admin" and password "admin123"\nWhen the user submits the form\nThen the POST /aut-api/auth/login returns { success: true, token: "fake-jwt-token-12345", user: { id: 1, name: "Admin", username: "admin" } }, the token is stored in localStorage with key "aut_token", and the user is redirected to /aut',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 3,
  },

  // ── Story 3: Route Guard & Session Protection ──────────────────
  {
    id: 'req-aut-auth-route-guard',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth',
    title: 'Route Guard & Session Protection',
    description: 'As a user\nI want protected routes to check for a valid authentication token in localStorage and redirect unauthenticated users to the login page, and a Sign Out action that clears the token\nSo that my account and protected pages are secured against unauthorized access',
    level: 'story',
    status: 'APPROVED',
    position: 2,
  },
  {
    id: 'req-aut-auth-route-guard-redirect',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-route-guard',
    title: 'Unauthenticated access redirects to login',
    description: 'Given the user is not authenticated (localStorage does not contain an "aut_token" entry)\nWhen the user navigates to any protected route under /aut (e.g., /aut, /aut/users, /aut/reports)\nThen the ProtectedRoute component renders a <Navigate to="/aut/login" replace /> element and the browser URL changes to /aut/login without keeping the protected path in history',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-auth-route-guard-allow',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-route-guard',
    title: 'Authenticated access renders protected route',
    description: 'Given the user has a non-empty "aut_token" value in localStorage\nWhen the user navigates to a protected route under /aut\nThen the ProtectedRoute component renders the protected children (the Layout with sidebar and the matched page) and the user can interact with the page normally',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-auth-route-guard-signout',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-route-guard',
    title: 'Sign Out clears token and redirects to login',
    description: 'Given the user is authenticated and viewing the application shell\nWhen the user clicks the "Sign Out" link in the sidebar footer\nThen localStorage.removeItem("aut_token") is called to clear the token, and the user is navigated to /aut/login via the Link "to" prop\nAnd subsequent attempts to access protected routes redirect to /aut/login because the token is no longer present',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 2,
  },
  {
    id: 'req-aut-auth-route-guard-login-public',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-route-guard',
    title: 'Login page is publicly accessible without token',
    description: 'Given the user is not authenticated\nWhen the user navigates to /aut/login\nThen the LoginPage component is rendered directly (not wrapped in ProtectedRoute) and no redirect occurs, allowing the user to enter credentials',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 3,
  },

  // ═══════════════════════════════════════════════════════════════
  // Epic 2: Dashboard & Home
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'req-aut-dashboard',
    projectId: AUT_PROJECT_ID,
    parentId: null,
    title: 'Dashboard & Home',
    description: 'The home dashboard provides an overview of system status, user statistics, and quick navigation links to other sections of the application. Data is fetched from GET /aut-api/dashboard/stats on mount.',
    level: 'epic',
    status: 'APPROVED',
    position: 1,
  },

  // ── Story 0: Application Shell & Navigation ────────────────────
  {
    id: 'req-aut-shell',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-dashboard',
    title: 'Application Shell & Navigation',
    description: 'As an authenticated user\nI want a persistent application shell with a sidebar (Target AUT branding, 3 nav items: Home, User Management, Reports, and a Sign Out link) and a header showing the current page label\nSo that I can navigate between sections and identify the current page at a glance',
    level: 'story',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-shell-sidebar',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-shell',
    title: 'Sidebar with branding and 3 navigation items',
    description: 'Given the user is authenticated and viewing any protected page\nWhen the user views the left sidebar (w-64, bg-slate-900)\nThen a header section displays a blue shield icon and the text "Target AUT"\nAnd a navigation section displays 3 links: "Home" (HomeIcon, to="/aut"), "User Management" (Users icon, to="/aut/users"), and "Reports" (BarChart icon, to="/aut/reports")',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-shell-active-highlight',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-shell',
    title: 'Active navigation item highlighting',
    description: 'Given the user is viewing a protected page\nWhen the current URL pathname matches a nav item path (exact match for /aut, or startsWith for /aut/users and /aut/reports)\nThen the matching nav item is highlighted with bg-blue-600 and white text\nAnd all other nav items display with text-slate-300 and a hover effect (bg-slate-800, text-white)',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-shell-header',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-shell',
    title: 'Header displays current page label',
    description: 'Given the user is viewing a protected page\nWhen the user views the top header bar (h-16, bg-white, border-b)\nThen the header displays the label of the current nav item ("Home" for /aut, "User Management" for /aut/users, "Reports" for /aut/reports) as a text-lg font-semibold heading\nAnd if no nav item matches, the fallback text "AUT App" is displayed',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 2,
  },
  {
    id: 'req-aut-shell-signout',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-shell',
    title: 'Sign Out link in sidebar footer',
    description: 'Given the user is viewing any protected page\nWhen the user views the sidebar footer section (border-t border-slate-800)\nThen a "Sign Out" link with a LogOut icon is displayed\nAnd when clicked, the link calls localStorage.removeItem("aut_token") via the onClick handler and navigates to /aut/login via the Link "to" prop',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 3,
  },
  {
    id: 'req-aut-shell-content-area',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-shell',
    title: 'Content area renders matched route via Outlet',
    description: 'Given the user is viewing a protected page\nWhen the user navigates between /aut, /aut/users, and /aut/reports\nThen the main content area (flex-1, p-8, overflow-auto) renders the corresponding page component (Home, UserManagement, or Reports) via the React Router <Outlet /> element\nAnd the sidebar and header remain persistent across page transitions',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 4,
  },

  // ── Story 1: Dashboard Layout ──────────────────────────────────
  {
    id: 'req-aut-dashboard-layout',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-dashboard',
    title: 'Dashboard Layout',
    description: 'As an admin\nI want the dashboard to show a welcome banner with a description, quick action links to Manage Users and View Reports, and three stat cards for Total Users, Active Sessions, and System Status\nSo that I can quickly understand system status and navigate to key sections',
    level: 'story',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-dashboard-layout-welcome',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-dashboard-layout',
    title: 'Welcome banner',
    description: 'Given the user is logged in and navigates to /aut\nWhen the dashboard loads\nThen a welcome banner is displayed with the heading "Welcome back, Admin!" (id="home-welcome") and the description "This is the central hub for the Target App Demo. From here you can check system status, manage your users, and configure application settings."',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-dashboard-layout-quick-actions',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-dashboard-layout',
    title: 'Quick action links',
    description: 'Given the user is on the dashboard\nWhen the user views the welcome banner\nThen two action links are displayed: "Manage Users" (blue button with ArrowRight icon, navigates to /aut/users) and "View Reports" (white button with border, navigates to /aut/reports)',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-dashboard-layout-total-users',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-dashboard-layout',
    title: 'Total Users stat card',
    description: 'Given the dashboard has loaded data from GET /aut-api/dashboard/stats\nWhen the user views the first stat card\nThen a card with Users icon (blue background) is displayed showing the heading "Total Users", the numeric value from stats.totalUsers, and the subtitle "Across all roles"',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 2,
  },
  {
    id: 'req-aut-dashboard-layout-active-sessions',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-dashboard-layout',
    title: 'Active Sessions stat card',
    description: 'Given the dashboard has loaded data from GET /aut-api/dashboard/stats\nWhen the user views the second stat card\nThen a card with Bell icon (emerald background) is displayed showing the heading "Active Sessions", the numeric value from stats.activeUsers, and the subtitle "Currently online"',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 3,
  },
  {
    id: 'req-aut-dashboard-layout-system-status',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-dashboard-layout',
    title: 'System Status stat card',
    description: 'Given the dashboard has loaded\nWhen the user views the third stat card\nThen a card with Settings icon (purple background) is displayed showing the heading "System Status", a green pulsing dot, the text "All systems operational" in emerald color, and the subtitle "Last checked just now"',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 4,
  },

  // ── Story 2: Dashboard Stats ───────────────────────────────────
  {
    id: 'req-aut-dashboard-stats',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-dashboard',
    title: 'Dashboard Stats Data Loading',
    description: 'As an admin\nI want the dashboard stat cards to fetch real-time data from the backend API on page mount\nSo that I can monitor the current system state at a glance',
    level: 'story',
    status: 'APPROVED',
    position: 2,
  },
  {
    id: 'req-aut-dashboard-stats-fetch',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-dashboard-stats',
    title: 'Stats API fetch on mount',
    description: 'Given the user navigates to the dashboard\nWhen the Home component mounts\nThen a GET request is made to /aut-api/dashboard/stats and the response data (totalUsers, activeUsers, recentRegistrations) is used to populate the stat cards',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-dashboard-stats-loading',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-dashboard-stats',
    title: 'Loading placeholder before data',
    description: 'Given the dashboard is fetching stats from the API\nWhen the data has not yet arrived\nThen the Total Users and Active Sessions cards display "-" as a placeholder until the real values are loaded',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 1,
  },

  // ═══════════════════════════════════════════════════════════════
  // Epic 3: User Management
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'req-aut-um',
    projectId: AUT_PROJECT_ID,
    parentId: null,
    title: 'User Management',
    description: 'Comprehensive user management covering list and filtering (name search, role/status dropdowns, Apply/Reset), sorting and pagination (6 sortable columns, 10 per page, page info), Quick Add modal (name, email, role, status), Advanced Add form (4 sections with cascader, permissions, slider, 2FA toggle, profile picture, async validation), view modal (5 sections), edit form (pre-filled advanced form), delete (confirm dialog), batch operations (activate/deactivate/delete with mixed-status warning), action drawer (reset password, export, suspend, delete), and the end-to-end user management flow.',
    level: 'epic',
    status: 'APPROVED',
    position: 2,
  },

  // ── Story 1: User List & Filtering ─────────────────────────────
  {
    id: 'req-aut-um-list',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um',
    title: 'User List & Filtering',
    description: 'As an admin\nI want to view all users in a table with checkbox, Name, Email, Role, Status, Created At, Last Modified, and Actions columns, and filter them by name (text search), role (dropdown: All/Admin/Editor/Viewer), and status (dropdown: All/Active/Inactive) with Apply and Reset controls\nSo that I can quickly find specific users',
    level: 'story',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-um-list-table',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-list',
    title: 'Table display with 8 columns',
    description: 'Given the user navigates to /aut/users\nWhen the user list loads from GET /aut-api/users\nThen a table is displayed with 8 columns: checkbox (select all), Name (sortable), Email (sortable), Role (sortable, capitalized), Status (sortable, green badge for Active, gray badge for Inactive), Created At (sortable, formatted date), Last Modified (sortable, formatted date), and Actions (4 buttons: View/Eye, Edit/Pencil, Delete/Trash, More/MoveHorizontal)',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-um-list-search-name',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-list',
    title: 'Name search with Apply',
    description: 'Given the user is on the User Management page\nWhen the user enters text in the name search input (id="filter-name", placeholder "e.g. John...") and clicks Apply\nThen the table is filtered via GET /aut-api/users?name=<text> to show only users whose names contain the search text (case-insensitive)',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-um-list-filter-role',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-list',
    title: 'Role filter dropdown',
    description: 'Given the user is on the User Management page\nWhen the user selects a role from the Role dropdown (id="filter-role", options: All Roles, Admin, Editor, Viewer) and clicks Apply\nThen the table is filtered via GET /aut-api/users?role=<value> to show only users with the selected role',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 2,
  },
  {
    id: 'req-aut-um-list-filter-status',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-list',
    title: 'Status filter dropdown',
    description: 'Given the user is on the User Management page\nWhen the user selects a status from the Status dropdown (id="filter-status", options: All Statuses, Active, Inactive) and clicks Apply\nThen the table is filtered via GET /aut-api/users?status=<value> to show only users with the selected status',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 3,
  },
  {
    id: 'req-aut-um-list-apply-reset',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-list',
    title: 'Apply and Reset filter controls',
    description: 'Given the user has entered filter values on the User Management page\nWhen the user clicks the Apply button (dark background with Filter icon)\nThen the filters are applied and the page resets to page 1\nAnd when the user clicks the Reset button (white with RefreshCcw icon)\nThen all filter inputs and applied filters are cleared, and the table shows all users on page 1',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 4,
  },
  {
    id: 'req-aut-um-list-empty',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-list',
    title: 'Empty state and loading skeleton',
    description: 'Given the user is on the User Management page\nWhen the table is loading and no users exist yet\nThen skeleton rows with pulse animation are displayed\nAnd when the API returns zero users\nThen a centered "No users found" message is displayed spanning all 8 columns',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 5,
  },

  // ── Story 2: User Table Sorting & Pagination ───────────────────
  {
    id: 'req-aut-um-sorting-pagination',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um',
    title: 'User Table Sorting & Pagination',
    description: 'As an admin\nI want to sort the user table by 6 columns (name, email, role, status, createdAt, updatedAt) with asc/desc toggle, and paginate through records at 10 per page with page navigation and count info\nSo that I can browse users efficiently regardless of dataset size',
    level: 'story',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-um-sorting-pagination-sort',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-sorting-pagination',
    title: 'Column sort with asc/desc toggle',
    description: 'Given the user is viewing the user table\nWhen the user clicks a sortable column header (name, email, role, status, createdAt, or updatedAt)\nThen the table is sorted by that column via GET /aut-api/users?sortBy=<field>&sortOrder=<asc|desc>\nAnd if the same column is clicked again, the sort order toggles between asc and desc with a blue chevron icon indicator\nAnd if a new column is clicked, the sort starts with desc order\nAnd the default sort on page load is sortBy=updatedAt&sortOrder=desc',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-um-sorting-pagination-nav',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-sorting-pagination',
    title: 'Pagination navigation at 10 per page',
    description: 'Given the user table contains more than 10 users\nWhen the user clicks a page number button or the Previous/Next arrow buttons\nThen the table displays the corresponding page of users via GET /aut-api/users?page=<n>&limit=10\nAnd the Previous button is disabled on page 1\nAnd the Next button is disabled on the last page',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-um-sorting-pagination-info',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-sorting-pagination',
    title: 'Page info display',
    description: 'Given the user is viewing a paginated user table\nWhen the user views the pagination section\nThen the text "Showing X to Y of Z users" is displayed where X is the first record number on the current page, Y is the last record number, and Z is the total record count',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 2,
  },

  // ── Story 3: User Creation - Quick Add ───────────────────────
  {
    id: 'req-aut-um-create-simple',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um',
    title: 'User Creation - Quick Add Modal',
    description: 'As an admin\nI want a Quick Add modal (title "Quick Add User") with minimal fields for Full Name (required), Email Address (required), Role (dropdown: Administrator/Editor/Viewer, default Viewer), and Status (dropdown: Active/Inactive, default Inactive)\nSo that I can rapidly create new users without filling out a long form',
    level: 'story',
    status: 'APPROVED',
    position: 2,
  },
  {
    id: 'req-aut-um-create-simple-modal',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-create-simple',
    title: 'Quick Add modal opens with default values',
    description: 'Given the user is on the User Management page\nWhen the user clicks the Quick Add button\nThen a modal opens with title "Quick Add User", a close button (XCircle), and 4 fields: Full Name * (required), Email Address * (required, type=email), Role dropdown (options: Administrator, Editor, Viewer; default "Viewer"), and Status dropdown (options: Active, Inactive; default "Inactive")',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-um-create-simple-required',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-create-simple',
    title: 'Required field validation',
    description: 'Given the Quick Add modal is open\nWhen the user clicks Save with an empty Full Name or Email Address\nThen the browser native validation prevents submission and highlights the missing required fields',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-um-create-simple-save',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-create-simple',
    title: 'Save creates user and shows toast',
    description: 'Given the Quick Add modal is open with valid data\nWhen the user clicks Save\nThen a POST request is sent to /aut-api/users with the form data, the response user is created with auto-generated id and timestamps, the modal closes, a success toast "User saved successfully" is displayed, and the user table is refreshed',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 2,
  },
  {
    id: 'req-aut-um-create-simple-cancel',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-create-simple',
    title: 'Cancel closes modal without saving',
    description: 'Given the Quick Add modal is open\nWhen the user clicks the Cancel button or the XCircle close button\nThen the modal closes and no API request is sent',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 3,
  },

  // ── Story 4: User Creation - Advanced Form ─────────────────────
  {
    id: 'req-aut-um-create-advanced',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um',
    title: 'User Creation - Advanced Form',
    description: 'As an admin\nI want an Advanced Add form (title "Create Complex Profile") with 4 sections: Personal Details (Full Name, Email, Biography), Job Details (Role, Department cascader, Contract Period, Shift Time), Security & Settings (4 permission checkboxes, Access Level slider 1-5, Account Status radio, 2FA toggle), and Profile Picture (drag-and-drop upload), plus a "Verify User Data" async validation button\nSo that I can capture comprehensive user details during creation',
    level: 'story',
    status: 'APPROVED',
    position: 3,
  },
  {
    id: 'req-aut-um-create-advanced-sections',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-create-advanced',
    title: 'Advanced form opens with 4 sections',
    description: 'Given the user is on the User Management page\nWhen the user clicks the Advanced Add button\nThen a modal opens with title "Create Complex Profile" and 4 numbered sections: "1. Personal Details", "2. Job Details", "3. Security & Settings", and "4. Profile Picture", plus a "Verify User Data" button in the header and Cancel/Save Profile buttons in the footer',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-um-create-advanced-personal',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-create-advanced',
    title: 'Personal Details section',
    description: 'Given the Advanced Add modal is open\nWhen the user views section 1\nThen three fields are displayed: Full Name (required text input), Email Address (required email input), and Biography (textarea, 2 rows, optional)',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-um-create-advanced-cascader',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-create-advanced',
    title: 'Department cascader with 3-level hierarchy',
    description: 'Given the Advanced Add modal is open\nWhen the user clicks the Department cascader in section 2\nThen a 3-level cascading selector is displayed with options: Development → Frontend → {React, Vue} or Development → Backend → {Node.js, Python} or Design → {UI Design, UX Research}\nAnd when a leaf node is selected, the cascader closes and the selected path is displayed as "L1 / L2 / L3"',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 2,
  },
  {
    id: 'req-aut-um-create-advanced-job-details',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-create-advanced',
    title: 'Job Details section with Role, Contract Period, and Shift Time',
    description: 'Given the Advanced Add modal is open\nWhen the user views section 2\nThen four fields are displayed: Role (select with options "Administrator (Full Access)", "Editor (Write Access)", "Viewer (Read Only)"), Department cascader, Contract Period (dual date input with "to" separator), and Preferred Shift time (time input)',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 3,
  },
  {
    id: 'req-aut-um-create-advanced-permissions',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-create-advanced',
    title: 'Security permissions checkboxes',
    description: 'Given the Advanced Add modal is open\nWhen the user views section 3\nThen 4 permission checkboxes are displayed in a 2-column grid: View Reports, Manage Users, Billing Access, and API Access, each in a bordered card with checkbox and label',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 4,
  },
  {
    id: 'req-aut-um-create-advanced-access-slider',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-create-advanced',
    title: 'Access Level slider 1-5',
    description: 'Given the Advanced Add modal is open\nWhen the user views section 3\nThen an Access Level range slider (min=1, max=5, default=3) is displayed with a badge showing "Level N" that updates as the slider moves',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 5,
  },
  {
    id: 'req-aut-um-create-advanced-2fa-status',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-create-advanced',
    title: 'Account Status radio and 2FA toggle',
    description: 'Given the Advanced Add modal is open\nWhen the user views section 3\nThen an Account Status radio group is displayed with two options: Active (emerald) and Inactive (gray, default)\nAnd a Two-Factor Authentication toggle switch is displayed with the description "Require 2FA codes during login", defaulting to off (gray)',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 6,
  },
  {
    id: 'req-aut-um-create-advanced-profile-pic',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-create-advanced',
    title: 'Profile Picture drag-and-drop upload',
    description: 'Given the Advanced Add modal is open\nWhen the user views section 4\nThen a drag-and-drop zone is displayed with a dashed border, Upload icon, and text "Drag an image here or Browse"\nAnd when a file is dragged or browsed, the filename is displayed in blue text',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 7,
  },
  {
    id: 'req-aut-um-create-advanced-verify',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-create-advanced',
    title: 'Verify User Data async validation',
    description: 'Given the Advanced Add modal is open\nWhen the user clicks the "Verify User Data" button\nThen the button text changes to "Running Security Check..." and is disabled for 3 seconds\nAnd after 3 seconds, a "Security Check Passed" modal is displayed with the message "No conflicts detected in active directories. Email domain is valid. User data verified." and an Acknowledge button',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 8,
  },
  {
    id: 'req-aut-um-create-advanced-save',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-create-advanced',
    title: 'Save Profile creates user',
    description: 'Given the Advanced Add modal is open with valid data\nWhen the user clicks Save Profile\nThen a POST request is sent to /aut-api/users with the form data (excluding avatar), the user is created, the modal closes, a success toast "User saved successfully" is displayed, and the table is refreshed',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 9,
  },

  // ── Story 5: User View & Edit ──────────────────────────────────
  {
    id: 'req-aut-um-view-edit',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um',
    title: 'User View & Edit',
    description: 'As an admin\nI want to view user details in a read-only modal (title "User Profile Details") with 5 sections and edit users through a pre-filled Advanced form (title "Edit Complex Profile")\nSo that I can review and update user records accurately',
    level: 'story',
    status: 'APPROVED',
    position: 4,
  },
  {
    id: 'req-aut-um-view-edit-view',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-view-edit',
    title: 'View modal with 5 sections',
    description: 'Given the user is viewing the user table\nWhen the user clicks the View action (Eye icon) on a row\nThen a read-only modal opens with title "User Profile Details" and 5 sections: "1. Personal Details" (Full Name, Email, Biography), "2. Job Details" (Role, Department, Contract Period, Shift Time), "3. Security & Settings" (Permissions, Access Level bar, Account Status, 2FA), "4. Profile Picture" (placeholder with Upload icon), and "5. Metadata" (Created At, Last Update), with a "Done Viewing" button at the bottom',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-um-view-edit-edit',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-view-edit',
    title: 'Edit form pre-filled with user data',
    description: 'Given the user is viewing the user table\nWhen the user clicks the Edit action (Pencil icon) on a row\nThen the Advanced form modal opens with title "Edit Complex Profile" and all fields (Personal Details, Job Details, Security & Settings, Profile Picture) are pre-filled with the user\'s current data from the table row',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-um-view-edit-save',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-view-edit',
    title: 'Save update via PUT request',
    description: 'Given the Edit form is open with modified data\nWhen the user clicks Save Profile\nThen a PUT request is sent to /aut-api/users/:id with the modified form data, the user record is updated with a new updatedAt timestamp, the modal closes, a success toast "User saved successfully" is displayed, and the table is refreshed',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 2,
  },

  // ── Story 6: User Delete ───────────────────────────────────────
  {
    id: 'req-aut-um-delete',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um',
    title: 'User Delete',
    description: 'As an admin\nI want to delete users via a browser confirm dialog ("Are you sure you want to delete this user?") and see a success toast and refreshed table\nSo that I can remove users safely without accidental deletion',
    level: 'story',
    status: 'APPROVED',
    position: 5,
  },
  {
    id: 'req-aut-um-delete-confirm',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-delete',
    title: 'Confirm dialog before deletion',
    description: 'Given the user is viewing the user table\nWhen the user clicks the Delete action (Trash icon) on a row\nThen a browser confirm dialog is displayed with the message "Are you sure you want to delete this user?"\nAnd if the user cancels, no deletion occurs',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-um-delete-success',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-delete',
    title: 'Delete success with toast',
    description: 'Given the delete confirmation dialog is displayed\nWhen the user confirms the deletion\nThen a DELETE request is sent to /aut-api/users/:id, the response confirms success, a success toast "User deleted successfully" is displayed, and the user table is refreshed',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-um-delete-failure',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-delete',
    title: 'Delete failure toast',
    description: 'Given the user confirms deletion\nWhen the DELETE request to /aut-api/users/:id fails or returns an error\nThen a failure toast "Delete failed" is displayed',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 2,
  },

  // ── Story 7: Batch Operations ──────────────────────────────────
  {
    id: 'req-aut-um-batch',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um',
    title: 'Batch Operations',
    description: 'As an admin\nI want to select multiple users via individual checkboxes or select-all, and perform batch activate, deactivate, or delete operations with a mixed-status warning badge and a Deselect option\nSo that I can manage many users efficiently',
    level: 'story',
    status: 'APPROVED',
    position: 6,
  },
  {
    id: 'req-aut-um-batch-select-all',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-batch',
    title: 'Select all on current page',
    description: 'Given the user is viewing the user table\nWhen the user clicks the header checkbox in the table\nThen all visible users on the current page are selected (their IDs added to selectedIds)\nAnd when clicked again, all selections on the current page are cleared',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-um-batch-action-bar',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-batch',
    title: 'Batch action bar appears on selection',
    description: 'Given one or more users are selected via checkbox\nWhen the selection count is greater than 0\nThen a blue batch action bar appears at the bottom of the table showing a "N Selected" badge (with count in a blue circle) and operation buttons',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-um-batch-activate',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-batch',
    title: 'Batch activate when all selected are inactive',
    description: 'Given multiple inactive users are selected\nWhen the user clicks the Activate All button (emerald, shown only when all selected are inactive)\nThen a POST request is sent to /aut-api/users/batch-update with { ids: selectedIds, data: { status: "active" } }, a toast "Updated N users" is displayed, selections are cleared, and the table is refreshed',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 2,
  },
  {
    id: 'req-aut-um-batch-deactivate',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-batch',
    title: 'Batch deactivate when all selected are active',
    description: 'Given multiple active users are selected\nWhen the user clicks the Deactivate All button (gray, shown only when all selected are active)\nThen a POST request is sent to /aut-api/users/batch-update with { ids: selectedIds, data: { status: "inactive" } }, a toast "Updated N users" is displayed, selections are cleared, and the table is refreshed',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 3,
  },
  {
    id: 'req-aut-um-batch-delete',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-batch',
    title: 'Batch delete with confirmation',
    description: 'Given multiple users are selected\nWhen the user clicks the Delete Selected button (red border) and confirms the dialog "Are you sure you want to delete N users?"\nThen a POST request is sent to /aut-api/users/batch-delete with { ids: selectedIds }, a toast "Deleted N users" is displayed, selections are cleared, and the table is refreshed',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 4,
  },
  {
    id: 'req-aut-um-batch-mixed',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-batch',
    title: 'Mixed status warning disables activate/deactivate',
    description: 'Given users with mixed active and inactive statuses are selected\nWhen the user views the batch action bar\nThen an amber warning badge is displayed with the text "Mixed statuses: Batch status update disabled" and both the Activate All and Deactivate All buttons are hidden (only Delete Selected and Deselect remain available)',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 5,
  },
  {
    id: 'req-aut-um-batch-deselect',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-batch',
    title: 'Deselect clears all selections',
    description: 'Given one or more users are selected\nWhen the user clicks the Deselect link in the batch action bar\nThen all selections are cleared (selectedIds becomes empty) and the batch action bar disappears',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 6,
  },

  // ── Story 8: User Action Drawer ────────────────────────────────
  {
    id: 'req-aut-um-drawer',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um',
    title: 'User Action Drawer',
    description: 'As an admin\nI want a slide-in drawer (from right, max-w-sm) with per-user actions for Send Password Reset, Export User Data, Suspend Account, and Permanently Delete, organized in Account Management and Danger Zone sections\nSo that I can perform administrative actions without leaving the user list',
    level: 'story',
    status: 'APPROVED',
    position: 7,
  },
  {
    id: 'req-aut-um-drawer-open',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-drawer',
    title: 'Drawer opens with user info',
    description: 'Given the user is viewing the user table\nWhen the user clicks the More Options action (MoveHorizontal icon) on a row\nThen a drawer slides in from the right with a header showing "User Actions" and the selected user\'s name, a footer showing "User ID: X • Last Login: Just now", and two sections: "Account Management" and "Danger Zone"',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-um-drawer-reset',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-drawer',
    title: 'Send Password Reset',
    description: 'Given the action drawer is open for a user\nWhen the user clicks "Send Password Reset" in the Account Management section\nThen a POST request is sent to /aut-api/users/:id/reset-password, a success toast "Password reset link sent successfully" is displayed, and the drawer closes',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-um-drawer-export',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-drawer',
    title: 'Export User Data as JSON',
    description: 'Given the action drawer is open for a user\nWhen the user clicks "Export User Data" in the Account Management section\nThen the user\'s data is downloaded as a JSON file named "user_<id>_export.json" and a toast "User data exported" is displayed',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 2,
  },
  {
    id: 'req-aut-um-drawer-suspend',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-drawer',
    title: 'Suspend Account with confirmation',
    description: 'Given the action drawer is open for a user\nWhen the user clicks "Suspend Account" in the Danger Zone section and confirms the dialog "Are you sure you want to suspend this account?"\nThen a PATCH request is sent to /aut-api/users/:id with { status: "inactive" }, a toast "Account suspended" is displayed, and the drawer closes',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 3,
  },
  {
    id: 'req-aut-um-drawer-delete',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-drawer',
    title: 'Permanently Delete from drawer',
    description: 'Given the action drawer is open for a user\nWhen the user clicks "Permanently Delete" in the Danger Zone section and confirms the dialog\nThen a DELETE request is sent to /aut-api/users/:id, the user is deleted, and the drawer closes',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 4,
  },

  // ═══════════════════════════════════════════════════════════════
  // Epic 4: Reports & Analytics
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'req-aut-reports',
    projectId: AUT_PROJECT_ID,
    parentId: null,
    title: 'Reports & Analytics',
    description: 'Visual data reports page (title "System Reports") fetched from GET /aut-api/reports, including 4 summary cards (Total Users, Active Accounts, Admins, Engagement Rate), a donut pie chart for User Role Distribution (admin/editor/viewer), and a bar chart for Users by Department, with a loading spinner during data fetch.',
    level: 'epic',
    status: 'APPROVED',
    position: 3,
  },

  // ── Story 1: Reports Dashboard ─────────────────────────────────
  {
    id: 'req-aut-reports-dashboard',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-reports',
    title: 'Reports Dashboard',
    description: 'As an admin\nI want the reports page to show a page title, 4 summary cards (Total Users, Active Accounts, Admins, Engagement Rate), a donut pie chart for role distribution, a bar chart for department distribution, and a loading spinner during fetch\nSo that I can visualize user distribution and system metrics',
    level: 'story',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-reports-dashboard-loading',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-reports-dashboard',
    title: 'Loading spinner during data fetch',
    description: 'Given the user navigates to /aut/reports\nWhen the reports data is being fetched from GET /aut-api/reports\nThen a blue spinning loader (animate-spin, border-b-2 border-blue-600) is displayed centered on the page until the data is loaded',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-reports-dashboard-cards',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-reports-dashboard',
    title: 'Four summary cards',
    description: 'Given the reports data has loaded\nWhen the user views the summary cards section\nThen 4 cards are displayed in a row: "Total Users" (Users icon, blue, value from data.totalUsers), "Active Accounts" (CheckCircle icon, emerald, value from data.activeUsers), "Admins" (ShieldCheck icon, purple, value from roleDistribution where name="admin"), and "Engagement Rate" (Activity icon, orange, percentage calculated as round(activeUsers/totalUsers*100)%)',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-reports-dashboard-pie',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-reports-dashboard',
    title: 'Donut pie chart for User Role Distribution',
    description: 'Given the reports data has loaded\nWhen the user views the first chart\nThen a donut pie chart titled "User Role Distribution" is displayed with innerRadius=60, outerRadius=80, paddingAngle=5, showing segments for admin, editor, and viewer from data.roleDistribution, with colors from the palette [#3b82f6, #10b981, #f59e0b, #ef4444, #8b5cf6], and includes Tooltip and Legend',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 2,
  },
  {
    id: 'req-aut-reports-dashboard-bar',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-reports-dashboard',
    title: 'Bar chart for Users by Department',
    description: 'Given the reports data has loaded\nWhen the user views the second chart\nThen a bar chart titled "Users by Department" is displayed with CartesianGrid (dashed horizontal lines), XAxis (dataKey="name"), YAxis, Tooltip (cursor fill), and blue bars (fill="#3b82f6", radius=[4,4,0,0]) showing count per department from data.departmentDistribution',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 3,
  },

  // ═══════════════════════════════════════════════════════════════
  // Epic 5: Fault Injection
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'req-aut-fault',
    projectId: AUT_PROJECT_ID,
    parentId: null,
    title: 'Fault Injection',
    description: 'Endpoints designed for testing error handling, timeouts, and content type variations in automated tests, including a 5-second delay endpoint, a random 500 error endpoint with 50% probability, and an XML content type response endpoint.',
    level: 'epic',
    status: 'APPROVED',
    position: 4,
  },

  // ── Story 1: Fault Injection Endpoints ─────────────────────────
  {
    id: 'req-aut-fault-endpoints',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-fault',
    title: 'Fault Injection Endpoints',
    description: 'As a tester\nI want fault injection endpoints for timeout (5s delay), random 500 (50% probability), and XML content type response\nSo that I can verify client error handling under adverse conditions',
    level: 'story',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-fault-endpoints-timeout',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-fault-endpoints',
    title: 'Timeout delay endpoint',
    description: 'Given the fault injection API is available\nWhen a request is made to GET /aut-api/fault/timeout\nThen the server waits 5000ms (5 seconds) before returning { success: true, message: "Delayed response" }',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-fault-endpoints-500',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-fault-endpoints',
    title: 'Random 500 error endpoint',
    description: 'Given the fault injection API is available\nWhen a request is made to GET /aut-api/fault/simulate-500\nThen the endpoint returns HTTP 500 with { success: false, error: "Simulated strict internal failure" } at approximately 50% probability, and returns { success: true, message: "Lucky you, it worked this time" } the other 50% of the time',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-fault-endpoints-xml',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-fault-endpoints',
    title: 'XML content type endpoint',
    description: 'Given the fault injection API is available\nWhen a request is made to GET /aut-api/fault/xml-content\nThen the response is returned with Content-Type header set to "application/xml" and the body is an XML string: <response><success>true</success><message>This is returned in XML format</message></response>',
    level: 'ac',
    flowType: 'atomic',
    status: 'APPROVED',
    position: 2,
  },

  // ═══════════════════════════════════════════════════════════════
  // Flow Stories (BDD Features) — placed after all functional stories
  // so relatedRequirementIds references resolve at save time.
  // Each flow story's parentId links it to its owning epic.
  // ═══════════════════════════════════════════════════════════════

  // ── Flow: Authentication Session (under Epic 1: AUTH) ──────────
  {
    id: 'req-aut-auth-session',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth',
    title: 'Authentication Session',
    description: 'As a user\nI want the authentication session to handle login form submission, API authentication, token storage in localStorage, and redirect on success, with error display and retry on failure\nSo that I can securely access the application after authentication',
    level: 'story',
    isFlow: true,
    status: 'APPROVED',
    position: 3,
  },
  {
    id: 'req-aut-auth-session-happy',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-session',
    title: 'Happy path: valid credentials authenticate and redirect to dashboard',
    description: 'Given the user is on the login page with valid credentials (admin/admin123)\nWhen the user enters the credentials and clicks Sign in\nThen the POST /aut-api/auth/login returns { success: true, token: "fake-jwt-token-12345" }, the token is stored in localStorage with key "aut_token", and the user is redirected to /aut (dashboard)',
    level: 'ac',
    flowType: 'flow',
    relatedRequirementIds: ['req-aut-auth-login-ui', 'req-aut-auth-login-validation'],
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-auth-session-invalid',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-session',
    title: 'Exception: invalid credentials show error and allow retry',
    description: 'Given the user is on the login page with invalid credentials (e.g., wrong password)\nWhen the user enters the credentials and clicks Sign in\nThen the POST /aut-api/auth/login returns 401 with { success: false, error: "Invalid credentials" }, the error message is displayed in the red error box (id="login-error"), the token is NOT stored, and the user can retry by entering different credentials',
    level: 'ac',
    flowType: 'flow',
    relatedRequirementIds: ['req-aut-auth-login-validation', 'req-aut-auth-login-ui'],
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-auth-session-empty',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-session',
    title: 'Exception: empty fields block form submission with validation error',
    description: 'Given the user is on the login page\nWhen the user clicks Sign in without filling in the username or password\nThen the error message "Please fill in all required fields." is displayed in the red error box (id="login-error"), no API request is sent, and the user can fill in the missing fields and retry',
    level: 'ac',
    flowType: 'flow',
    relatedRequirementIds: ['req-aut-auth-login-validation', 'req-aut-auth-login-ui'],
    status: 'APPROVED',
    position: 2,
  },

  // ── Flow: Login to Reports Journey (under Epic 1: AUTH) ────────
  {
    id: 'req-aut-auth-login-reports-flow',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth',
    title: 'Login to Reports Journey',
    description: 'As a user\nI want to log in and navigate to the reports page to view summary data, charts, and loading states\nSo that I can review system metrics after authentication',
    level: 'story',
    isFlow: true,
    status: 'APPROVED',
    position: 4,
  },
  {
    id: 'req-aut-auth-login-reports-flow-happy',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-login-reports-flow',
    title: 'Happy path: login then navigate to reports and verify data loads',
    description: 'Given the user is on the login page\nWhen the user logs in with admin/admin123 and navigates to /aut/reports\nThen a loading spinner is displayed while GET /aut-api/reports fetches data, and once loaded, 4 summary cards (Total Users, Active Accounts, Admins, Engagement Rate), a donut pie chart for User Role Distribution, and a bar chart for Users by Department are displayed',
    level: 'ac',
    flowType: 'flow',
    relatedRequirementIds: ['req-aut-auth-login-ui', 'req-aut-dashboard-layout', 'req-aut-reports-dashboard'],
    status: 'APPROVED',
    position: 0,
  },

  // ── Flow: Session Guard & Sign Out Journey (under Epic 1: AUTH) ─
  {
    id: 'req-aut-auth-session-guard-flow',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth',
    title: 'Session Guard & Sign Out Journey',
    description: 'As a user\nI want the session guard to block unauthorized access and the sign-out action to fully terminate my session\nSo that my account remains secure after logout and protected pages cannot be accessed without re-authentication',
    level: 'story',
    isFlow: true,
    status: 'APPROVED',
    position: 5,
  },
  {
    id: 'req-aut-auth-session-guard-flow-happy',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-session-guard-flow',
    title: 'Happy path: login, access protected page, sign out, verify redirect and re-access blocked',
    description: 'Given the user is on the login page\nWhen the user logs in with admin/admin123 (token stored in localStorage as "aut_token"), navigates to /aut/users (protected route renders successfully), then clicks the "Sign Out" link in the sidebar footer\nThen localStorage.removeItem("aut_token") is called, the user is redirected to /aut/login, and a subsequent direct navigation to /aut/users triggers ProtectedRoute to render <Navigate to="/aut/login" replace /> because the token is no longer present',
    level: 'ac',
    flowType: 'flow',
    relatedRequirementIds: ['req-aut-auth-login-validation', 'req-aut-auth-route-guard', 'req-aut-shell'],
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-auth-session-guard-flow-blocked',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-session-guard-flow',
    title: 'Exception: direct URL access to protected route without token redirects to login',
    description: 'Given the user is not authenticated (no "aut_token" in localStorage, e.g., new browser session or after sign out)\nWhen the user enters a protected URL directly in the address bar (e.g., /aut, /aut/users, /aut/reports)\nThen the ProtectedRoute component immediately renders <Navigate to="/aut/login" replace /> and the browser URL changes to /aut/login, preventing access to the protected content\nAnd the login page is displayed so the user can authenticate',
    level: 'ac',
    flowType: 'flow',
    relatedRequirementIds: ['req-aut-auth-route-guard', 'req-aut-auth-login-ui'],
    status: 'APPROVED',
    position: 1,
  },

  // ── Flow: User Management Flow (under Epic 3: UM) ──────────────
  {
    id: 'req-aut-um-flow',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um',
    title: 'User Management Flow',
    description: 'As an admin\nI want to create, view, edit, batch-activate, and delete users through end-to-end flows\nSo that I can manage the complete user lifecycle with verified results',
    level: 'story',
    isFlow: true,
    status: 'APPROVED',
    position: 8,
  },
  {
    id: 'req-aut-um-flow-happy',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-flow',
    title: 'Happy path: create user via Quick Add, view in list, edit, and verify changes',
    description: 'Given the admin is on the User Management page\nWhen the admin clicks Quick Add, fills in Full Name and Email, selects Role and Status, clicks Save, then views the new user in the table, clicks Edit, modifies fields, and clicks Save Profile\nThen the user record is created via POST /aut-api/users, displayed in the refreshed table, and the edits are persisted via PUT /aut-api/users/:id with a success toast "User saved successfully"',
    level: 'ac',
    flowType: 'flow',
    relatedRequirementIds: ['req-aut-um-create-simple', 'req-aut-um-list', 'req-aut-um-view-edit'],
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-um-flow-batch',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-flow',
    title: 'Alternate: select multiple inactive users, batch activate, and verify status changed',
    description: 'Given the admin has selected multiple inactive users via checkbox on the User Management page\nWhen the admin clicks the Activate All button in the batch action bar\nThen a POST request is sent to /aut-api/users/batch-update with { ids: selectedIds, data: { status: "active" } }, all selected users have their status changed to active, a toast "Updated N users" is displayed, selections are cleared, and the table is refreshed showing the updated statuses',
    level: 'ac',
    flowType: 'flow',
    relatedRequirementIds: ['req-aut-um-batch'],
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-um-flow-delete',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-flow',
    title: 'Exception: delete user and verify removed from list',
    description: 'Given the admin is viewing the user list\nWhen the admin clicks the Delete action on a row and confirms the dialog "Are you sure you want to delete this user?"\nThen a DELETE request is sent to /aut-api/users/:id, the user is removed from the database, a toast "User deleted successfully" is displayed, and the table is refreshed with the deleted user no longer appearing',
    level: 'ac',
    flowType: 'flow',
    relatedRequirementIds: ['req-aut-um-delete', 'req-aut-um-list'],
    status: 'APPROVED',
    position: 2,
  },
  {
    id: 'req-aut-um-flow-drawer',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-um-flow',
    title: 'Alternate: open action drawer, export user data, and suspend account',
    description: 'Given the admin is viewing the user list\nWhen the admin clicks the More Options icon, opens the action drawer, clicks Export User Data, then reopens the drawer and clicks Suspend Account and confirms\nThen the user data is downloaded as a JSON file named "user_<id>_export.json" with a toast "User data exported", and the user\'s status is set to inactive via PATCH /aut-api/users/:id with a toast "Account suspended"',
    level: 'ac',
    flowType: 'flow',
    relatedRequirementIds: ['req-aut-um-drawer', 'req-aut-um-list'],
    status: 'APPROVED',
    position: 3,
  },
];

export function seedRequirements(): void {
  const existing = requirementRepo.listByProject(AUT_PROJECT_ID);
  if (existing.length > 0) {
    Log.for('seed').info(`AUT requirements already seeded (${existing.length} found), skipping.`);
    return;
  }
  for (const req of requirements) {
    requirementRepo.save(req);
  }
  Log.for('seed').info(`Seeded ${requirements.length} AUT requirements.`);
}
