import { Log } from '../../shared/services/logger';
import type { Requirement } from '../../shared/contracts/index.ts';
import { requirementRepo } from './repository.ts';

const AUT_PROJECT_ID = 'p-aut-demo';

const requirements: Requirement[] = [
  // ══════════════════════════════════════�?  // Epic 1: Authentication System
  // ══════════════════════════════════════�?  {
    id: 'req-aut-auth',
    projectId: AUT_PROJECT_ID,
    parentId: null,
    title: 'Authentication System',
    description: 'Secure login and session management for the AUT application.',
    level: 'epic',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-auth-login-ui',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth',
    title: 'Login Page UI & UX',
    description: 'The login page provides a user-friendly authentication interface with form validation and password visibility toggle.',
    level: 'story',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-auth-login-ui-form',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-login-ui',
    title: 'Login Form Display',
    description: 'The login form must render correctly with all required fields and controls.',
    level: 'story',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-auth-login-ui-form-display',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-login-ui-form',
    title: 'Display login form with username and password fields',
    description: 'The login form must render username input with user icon, password input with lock icon, and submit button.',
    level: 'ac',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-auth-login-ui-form-loading',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-login-ui-form',
    title: 'Disable submit button and show loading state during authentication',
    description: 'When login request is in progress, the submit button must be disabled and display "Signing in..." text.',
    level: 'ac',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-auth-login-ui-validation',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-login-ui',
    title: 'Form Validation & UX',
    description: 'The login form must validate input and provide good user experience with password visibility and utility controls.',
    level: 'story',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-auth-login-ui-validation-empty',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-login-ui-validation',
    title: 'Show validation error for empty fields',
    description: 'When username or password is empty on submit, display error message "Please fill in all required fields."',
    level: 'ac',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-auth-login-ui-validation-toggle',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-login-ui-validation',
    title: 'Toggle password visibility with eye icon',
    description: 'The password field must have a toggle button to show/hide password text using Eye/EyeOff icons.',
    level: 'ac',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-auth-login-ui-validation-remember',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-login-ui-validation',
    title: 'Show Remember me checkbox and Forgot password link',
    description: 'The form must include a "Remember me" checkbox and a "Forgot password?" link below the password field.',
    level: 'ac',
    status: 'APPROVED',
    position: 2,
  },
  {
    id: 'req-aut-auth-login-api',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth',
    title: 'Login Authentication API',
    description: 'The authentication API validates credentials and returns a token for session management.',
    level: 'story',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-auth-login-api-success',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-login-api',
    title: 'Successful Authentication',
    description: 'Valid credentials must be accepted and result in a successful login with token.',
    level: 'story',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-auth-login-api-success-valid',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-login-api-success',
    title: 'Authenticate with admin/admin123 credentials',
    description: 'POST /aut-api/auth/login with username "admin" and password "admin123" must return success with a JWT token.',
    level: 'ac',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-auth-login-api-success-token',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-login-api-success',
    title: 'Store token in localStorage and redirect to dashboard',
    description: 'On successful login, the token must be stored as "aut_token" in localStorage and navigate to /aut.',
    level: 'ac',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-auth-login-api-errors',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-login-api',
    title: 'Error Handling',
    description: 'Invalid credentials and network failures must be handled gracefully with appropriate error messages.',
    level: 'story',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-auth-login-api-errors-invalid',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-login-api-errors',
    title: 'Return 401 for invalid credentials',
    description: 'POST /aut-api/auth/login with wrong credentials must return status 401 with error message "Invalid credentials".',
    level: 'ac',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-auth-login-api-errors-network',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-auth-login-api-errors',
    title: 'Handle network errors gracefully',
    description: 'If the login request fails due to network error, display "Network error occurred" message.',
    level: 'ac',
    status: 'APPROVED',
    position: 1,
  },

  // ══════════════════════════════════════�?  // Epic 2: Dashboard
  // ══════════════════════════════════════�?  {
    id: 'req-aut-dashboard',
    projectId: AUT_PROJECT_ID,
    parentId: null,
    title: 'Dashboard',
    description: 'The home dashboard provides an overview of system status, user statistics, and quick navigation links.',
    level: 'epic',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-dashboard-home-ui',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-dashboard',
    title: 'Dashboard Home Page',
    description: 'The dashboard landing page displays key metrics and navigation to other sections.',
    level: 'story',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-dashboard-home-ui-welcome',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-dashboard-home-ui',
    title: 'Welcome & Navigation',
    description: 'The dashboard must greet the user and provide quick links to major sections.',
    level: 'story',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-dashboard-home-ui-welcome-greeting',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-dashboard-home-ui-welcome',
    title: 'Display welcome message for authenticated user',
    description: 'The dashboard must display "Welcome back, Admin!" heading with a descriptive subtitle.',
    level: 'ac',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-dashboard-home-ui-welcome-nav',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-dashboard-home-ui-welcome',
    title: 'Provide navigation links to Users and Reports pages',
    description: 'The dashboard must have a "Manage Users" button linking to /aut/users and a "View Reports" button linking to /aut/reports.',
    level: 'ac',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-dashboard-home-ui-stats',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-dashboard-home-ui',
    title: 'Statistics Display',
    description: 'The dashboard must display real-time system metrics in stat cards.',
    level: 'story',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-dashboard-home-ui-stats-cards',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-dashboard-home-ui-stats',
    title: 'Show stat cards for Total Users, Active Sessions, and System Status',
    description: 'Three stat cards must display: total user count, active users count (with green dot), and system status with pulsing online indicator.',
    level: 'ac',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-dashboard-home-api',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-dashboard',
    title: 'Dashboard Statistics API',
    description: 'The dashboard fetches real-time statistics from the server.',
    level: 'story',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-dashboard-home-api-fetch',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-dashboard-home-api',
    title: 'Data Fetching',
    description: 'The dashboard API must return aggregated statistics from the user database.',
    level: 'story',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-dashboard-home-api-fetch-stats',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-dashboard-home-api-fetch',
    title: 'GET /aut-api/dashboard/stats returns user statistics',
    description: 'The API must return totalUsers count, activeUsers count, and recentRegistrations list from the user database.',
    level: 'ac',
    status: 'APPROVED',
    position: 0,
  },

  // ══════════════════════════════════════�?  // Epic 3: User Management
  // ══════════════════════════════════════�?  {
    id: 'req-aut-user-mgmt',
    projectId: AUT_PROJECT_ID,
    parentId: null,
    title: 'User Management',
    description: 'Comprehensive user management with CRUD operations, batch actions, advanced form controls, and filtering capabilities.',
    level: 'epic',
    status: 'APPROVED',
    position: 2,
  },
  {
    id: 'req-aut-user-mgmt-list',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt',
    title: 'User List View',
    description: 'The user list displays all users in a table with sorting, filtering, pagination, and loading states.',
    level: 'story',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-user-mgmt-list-table',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-list',
    title: 'Table Display & Sorting',
    description: 'The user table must display data with sortable columns for easy browsing.',
    level: 'story',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-user-mgmt-list-table-display',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-list-table',
    title: 'Display user table with Name, Email, Role, Status, and date columns',
    description: 'The table must show columns: Name, Email, Role, Status (with colored badge), Created At, Last Modified, and Actions.',
    level: 'ac',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-user-mgmt-list-table-sort',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-list-table',
    title: 'Sort users by clicking column headers',
    description: 'Clicking Name, Email, Role, Status, Created At, or Last Modified headers must toggle ascending/descending sort with visual indicator.',
    level: 'ac',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-user-mgmt-list-filter',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-list',
    title: 'Filtering',
    description: 'Users must be filterable by text search and dropdown selections.',
    level: 'story',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-user-mgmt-list-filter-inputs',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-list-filter',
    title: 'Filter users by name search, role dropdown, and status dropdown',
    description: 'Users must be filterable by: text search on name, role selection (All/Admin/Editor/Viewer), and status selection (All/Active/Inactive).',
    level: 'ac',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-user-mgmt-list-pagination',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-list',
    title: 'Pagination & Loading',
    description: 'The table must paginate results and show appropriate loading states.',
    level: 'story',
    status: 'APPROVED',
    position: 2,
  },
  {
    id: 'req-aut-user-mgmt-list-pagination-nav',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-list-pagination',
    title: 'Support pagination with page number buttons and navigation',
    description: 'The table must paginate results (10 per page) with page number buttons, previous/next arrows, and "X to Y of Z" record count text.',
    level: 'ac',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-user-mgmt-list-pagination-loading',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-list-pagination',
    title: 'Show loading skeleton and syncing overlay',
    description: 'Initial load must show animated skeleton rows. Subsequent fetches show a "Syncing Data..." overlay with spinner.',
    level: 'ac',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-user-mgmt-list-pagination-empty',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-list-pagination',
    title: 'Display empty state when no users match filters',
    description: 'When no users are found, the table must display "No users found" message spanning all columns.',
    level: 'ac',
    status: 'APPROVED',
    position: 2,
  },
  {
    id: 'req-aut-user-mgmt-quick-add',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt',
    title: 'Quick Add User',
    description: 'A simple modal form for quickly creating a new user with basic fields.',
    level: 'story',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-user-mgmt-quick-add-form',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-quick-add',
    title: 'Simple Creation Form',
    description: 'The Quick Add modal provides a minimal form for rapid user creation.',
    level: 'story',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-user-mgmt-quick-add-form-modal',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-quick-add-form',
    title: 'Open modal form with name, email, role, and status fields',
    description: 'The Quick Add modal must contain: Full Name (required), Email (required), Role dropdown, and Status dropdown with Cancel/Save buttons.',
    level: 'ac',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-user-mgmt-advanced-form',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt',
    title: 'Advanced User Form',
    description: 'A comprehensive form with rich controls including cascading department selector, permissions, drag-and-drop upload, and more.',
    level: 'story',
    status: 'APPROVED',
    position: 2,
  },
  {
    id: 'req-aut-user-mgmt-advanced-form-personal',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-advanced-form',
    title: 'Personal Details',
    description: 'The advanced form must capture basic personal information.',
    level: 'story',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-user-mgmt-advanced-form-personal-fields',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-advanced-form-personal',
    title: 'Personal details section with name, email, and biography',
    description: 'The Personal Details section must include Full Name, Email Address, and Biography textarea fields.',
    level: 'ac',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-user-mgmt-advanced-form-job',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-advanced-form',
    title: 'Job Configuration',
    description: 'The form must capture job-related details with rich controls.',
    level: 'story',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-user-mgmt-advanced-form-job-cascader',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-advanced-form-job',
    title: 'Cascading department tree selector',
    description: 'The department selector must support 3-level cascading: Development > Frontend/Backend > React/Vue/Node.js/Python, and Design > UI Design/UX Research.',
    level: 'ac',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-user-mgmt-advanced-form-job-dates',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-advanced-form-job',
    title: 'Contract period date range picker',
    description: 'The Job Details section must include start date and end date native date inputs with a "to" separator.',
    level: 'ac',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-user-mgmt-advanced-form-security',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-advanced-form',
    title: 'Security Settings',
    description: 'The form must configure security-related settings with various control types.',
    level: 'story',
    status: 'APPROVED',
    position: 2,
  },
  {
    id: 'req-aut-user-mgmt-advanced-form-security-permissions',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-advanced-form-security',
    title: 'System permissions via checkboxes and access level slider',
    description: 'The Security section must include permission checkboxes (view_reports, manage_users, billing_access, api_access) and a 1-5 range slider for access level.',
    level: 'ac',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-user-mgmt-advanced-form-security-2fa',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-advanced-form-security',
    title: 'Two-factor authentication toggle switch',
    description: 'A toggle switch must allow enabling/disabling two-factor authentication with a styled sliding control.',
    level: 'ac',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-user-mgmt-advanced-form-security-avatar',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-advanced-form-security',
    title: 'Avatar upload via drag-and-drop',
    description: 'A drag-and-drop zone must accept image files for avatar upload, showing the filename after selection.',
    level: 'ac',
    status: 'APPROVED',
    position: 2,
  },
  {
    id: 'req-aut-user-mgmt-edit',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt',
    title: 'Edit User',
    description: 'Edit existing user details through the advanced form pre-filled with current data.',
    level: 'story',
    status: 'APPROVED',
    position: 3,
  },
  {
    id: 'req-aut-user-mgmt-edit-flow',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-edit',
    title: 'Edit Flow',
    description: 'Editing a user must pre-load existing data into the form.',
    level: 'story',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-user-mgmt-edit-flow-preload',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-edit-flow',
    title: 'Pre-fill form with existing user data on edit',
    description: 'Clicking the edit button must open the advanced form with all fields populated from the selected user record.',
    level: 'ac',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-user-mgmt-delete',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt',
    title: 'Delete User',
    description: 'Delete individual users with confirmation.',
    level: 'story',
    status: 'APPROVED',
    position: 4,
  },
  {
    id: 'req-aut-user-mgmt-delete-flow',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-delete',
    title: 'Deletion Flow',
    description: 'Deleting a user must require confirmation before proceeding.',
    level: 'story',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-user-mgmt-delete-flow-confirm',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-delete-flow',
    title: 'Show confirmation dialog before single delete',
    description: 'Clicking the delete action button must show a browser confirm dialog before performing the delete request.',
    level: 'ac',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-user-mgmt-batch',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt',
    title: 'Batch Operations',
    description: 'Perform bulk actions on multiple selected users simultaneously.',
    level: 'story',
    status: 'APPROVED',
    position: 5,
  },
  {
    id: 'req-aut-user-mgmt-batch-select',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-batch',
    title: 'Multi-Select',
    description: 'Users must be selectable individually or in bulk via checkboxes.',
    level: 'story',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-user-mgmt-batch-select-checkboxes',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-batch-select',
    title: 'Select all or individual users via checkboxes',
    description: 'A header checkbox must select/deselect all visible users. Individual row checkboxes allow selective multi-select.',
    level: 'ac',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-user-mgmt-batch-select-bar',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-batch-select',
    title: 'Show batch action bar with selected count',
    description: 'When users are selected, a batch action bar must appear showing the count badge, Activate/Deactivate buttons, and Delete Selected button.',
    level: 'ac',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-user-mgmt-batch-actions',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-batch',
    title: 'Batch Actions',
    description: 'Batch operations must support status updates and deletion.',
    level: 'story',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-user-mgmt-batch-actions-activate',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-batch-actions',
    title: 'Batch activate or deactivate selected users',
    description: '"Activate All" must set status to active for all selected inactive users. "Deactivate All" must set status to inactive for selected active users.',
    level: 'ac',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-user-mgmt-batch-actions-delete',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-batch-actions',
    title: 'Batch delete selected users with confirmation',
    description: '"Delete Selected" must show a confirmation dialog with the count of users to be deleted before sending batch delete request.',
    level: 'ac',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-user-mgmt-batch-actions-mixed',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-batch-actions',
    title: 'Handle mixed status selection gracefully',
    description: 'When selected users have mixed active/inactive statuses, show warning badge and disable batch status update buttons.',
    level: 'ac',
    status: 'APPROVED',
    position: 2,
  },
  {
    id: 'req-aut-user-mgmt-actions',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt',
    title: 'User Action Utilities',
    description: 'Additional user actions including view details, export, password reset, and account suspension.',
    level: 'story',
    status: 'APPROVED',
    position: 6,
  },
  {
    id: 'req-aut-user-mgmt-actions-profile',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-actions',
    title: 'Profile & Export',
    description: 'Users can view detailed profiles and export data.',
    level: 'story',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-user-mgmt-actions-profile-view',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-actions-profile',
    title: 'View user profile details in read-only modal',
    description: 'Clicking the eye icon must open a detailed read-only view of user profile with all fields displayed.',
    level: 'ac',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-user-mgmt-actions-profile-export',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-actions-profile',
    title: 'Export user data as downloadable JSON file',
    description: 'The More Options menu must include an export action that downloads user data as a JSON file.',
    level: 'ac',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-user-mgmt-actions-admin',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-actions',
    title: 'Admin Utilities',
    description: 'Administrative actions for user account management.',
    level: 'story',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-user-mgmt-actions-admin-pw-reset',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-actions-admin',
    title: 'Trigger password reset email',
    description: 'The More Options menu must include a password reset action that calls POST /aut-api/users/:id/reset-password.',
    level: 'ac',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-user-mgmt-actions-admin-suspend',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-actions-admin',
    title: 'Suspend user account with confirmation',
    description: 'The More Options menu must include a suspend action that sets user status to inactive after confirmation.',
    level: 'ac',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-user-mgmt-api',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt',
    title: 'User Management API',
    description: 'RESTful API endpoints for all user CRUD operations, batch operations, and utility actions.',
    level: 'story',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-user-mgmt-api-list',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-api',
    title: 'List & Query',
    description: 'The API must support querying users with filtering, sorting, and pagination.',
    level: 'story',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-user-mgmt-api-list-endpoint',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-api-list',
    title: 'GET /aut-api/users returns paginated, filterable, sortable list',
    description: 'The endpoint must accept query params: name, role, status, search, page, limit, sortBy, sortOrder and return paginated results with total count.',
    level: 'ac',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-user-mgmt-api-crud',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-api',
    title: 'Create & Update',
    description: 'The API must support creating and updating user records.',
    level: 'story',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-user-mgmt-api-crud-create',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-api-crud',
    title: 'POST /aut-api/users creates user with name/email validation',
    description: 'The endpoint must validate that name and email are required strings, return 400 with error message if validation fails.',
    level: 'ac',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-user-mgmt-api-crud-update',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-api-crud',
    title: 'PUT and PATCH /aut-api/users/:id for updates',
    description: 'PUT must replace all fields. PATCH must support partial update. Both must update the updatedAt timestamp.',
    level: 'ac',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-user-mgmt-api-batch',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-api',
    title: 'Delete & Batch',
    description: 'The API must support single/batch deletion and batch updates.',
    level: 'story',
    status: 'APPROVED',
    position: 2,
  },
  {
    id: 'req-aut-user-mgmt-api-batch-delete',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-api-batch',
    title: 'DELETE endpoints for single and batch removal',
    description: 'DELETE /aut-api/users/:id removes single user. POST /aut-api/users/batch-delete removes multiple users by ID array.',
    level: 'ac',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-user-mgmt-api-batch-update',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-user-mgmt-api-batch',
    title: 'POST /aut-api/users/batch-update for mass updates',
    description: 'The endpoint must accept { ids: number[], data: object } and apply the data update to all specified users.',
    level: 'ac',
    status: 'APPROVED',
    position: 1,
  },

  // ══════════════════════════════════════�?  // Epic 4: Reports & Analytics
  // ══════════════════════════════════════�?  {
    id: 'req-aut-reports',
    projectId: AUT_PROJECT_ID,
    parentId: null,
    title: 'Reports & Analytics',
    description: 'Visual data reports including charts for user role distribution and department distribution.',
    level: 'epic',
    status: 'APPROVED',
    position: 3,
  },
  {
    id: 'req-aut-reports-stats',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-reports',
    title: 'Reports Stat Cards',
    description: 'Summary metric cards displayed at the top of the reports page.',
    level: 'story',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-reports-stats-metrics',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-reports-stats',
    title: 'Metric Display',
    description: 'The reports page must show key metrics as summary cards.',
    level: 'story',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-reports-stats-metrics-cards',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-reports-stats-metrics',
    title: 'Display stat cards for Total Users, Active Accounts, Admins, and Engagement Rate',
    description: 'Four metric cards must show: total user count, active account count, admin count, and engagement rate percentage.',
    level: 'ac',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-reports-role-chart',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-reports',
    title: 'Role Distribution Chart',
    description: 'A donut pie chart visualizing users by their assigned role.',
    level: 'story',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-reports-role-chart-pie',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-reports-role-chart',
    title: 'Pie Chart Visualization',
    description: 'The role distribution must be visualized as an interactive donut chart.',
    level: 'story',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-reports-role-chart-pie-display',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-reports-role-chart-pie',
    title: 'Display donut pie chart of users grouped by role with legend',
    description: 'The pie chart must show admin, editor, and viewer segments with different colors. A legend must show role names with corresponding colors.',
    level: 'ac',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-reports-dept-chart',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-reports',
    title: 'Department Distribution Chart',
    description: 'A bar chart displaying user count per department.',
    level: 'story',
    status: 'APPROVED',
    position: 2,
  },
  {
    id: 'req-aut-reports-dept-chart-bar',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-reports-dept-chart',
    title: 'Bar Chart Visualization',
    description: 'The department distribution must be visualized as an interactive bar chart.',
    level: 'story',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-reports-dept-chart-bar-display',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-reports-dept-chart-bar',
    title: 'Display bar chart of users per department with tooltip',
    description: 'A bar chart must show department names on X-axis and user counts on Y-axis with hover tooltips for exact values.',
    level: 'ac',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-reports-api',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-reports',
    title: 'Reports Data API',
    description: 'API endpoint serving aggregated report data for charts and metrics.',
    level: 'story',
    status: 'APPROVED',
    position: 3,
  },
  {
    id: 'req-aut-reports-api-aggregation',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-reports-api',
    title: 'Data Aggregation',
    description: 'The reports API must aggregate user data into chart-friendly formats.',
    level: 'story',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-reports-api-aggregation-endpoint',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-reports-api-aggregation',
    title: 'GET /aut-api/reports returns aggregated report data',
    description: 'The endpoint must return totalUsers, activeUsers, roleDistribution array, and departmentDistribution array computed from the user database.',
    level: 'ac',
    status: 'APPROVED',
    position: 0,
  },

  // ══════════════════════════════════════�?  // Epic 5: Fault Injection & Testing Utilities
  // ══════════════════════════════════════�?  {
    id: 'req-aut-fault',
    projectId: AUT_PROJECT_ID,
    parentId: null,
    title: 'Fault Injection & Testing Utilities',
    description: 'Endpoints designed for testing error handling, timeouts, and content type variations in automated tests.',
    level: 'epic',
    status: 'APPROVED',
    position: 4,
  },
  {
    id: 'req-aut-fault-timeout',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-fault',
    title: 'Timeout Simulation',
    description: 'Simulates a slow API response for testing timeout handling.',
    level: 'story',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-fault-timeout-delay',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-fault-timeout',
    title: 'Delayed Response',
    description: 'A configurable delay endpoint for testing client timeout behavior.',
    level: 'story',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-fault-timeout-delay-endpoint',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-fault-timeout-delay',
    title: 'GET /aut-api/fault/timeout returns response after 5-second delay',
    description: 'The endpoint must delay the response by 5000ms before returning a success JSON response.',
    level: 'ac',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-fault-error',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-fault',
    title: 'Error Simulation',
    description: 'Simulates server errors for testing error handling logic.',
    level: 'story',
    status: 'APPROVED',
    position: 1,
  },
  {
    id: 'req-aut-fault-error-500',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-fault-error',
    title: 'Server Error Testing',
    description: 'An endpoint that randomly returns 500 errors for testing error recovery.',
    level: 'story',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-fault-error-500-endpoint',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-fault-error-500',
    title: 'GET /aut-api/fault/simulate-500 returns 500 error with 50% probability',
    description: 'The endpoint must return HTTP 500 with error message 50% of the time, and success the other 50%.',
    level: 'ac',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-fault-xml',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-fault',
    title: 'XML Content Type Response',
    description: 'Returns XML formatted response for testing content type handling.',
    level: 'story',
    status: 'APPROVED',
    position: 2,
  },
  {
    id: 'req-aut-fault-xml-content',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-fault-xml',
    title: 'Content Type Testing',
    description: 'An endpoint that returns XML instead of JSON for testing content negotiation.',
    level: 'story',
    status: 'APPROVED',
    position: 0,
  },
  {
    id: 'req-aut-fault-xml-content-endpoint',
    projectId: AUT_PROJECT_ID,
    parentId: 'req-aut-fault-xml-content',
    title: 'GET /aut-api/fault/xml-content returns XML with proper content type',
    description: 'The endpoint must return XML formatted response with Content-Type header set to application/xml.',
    level: 'ac',
    status: 'APPROVED',
    position: 0,
  },
];

export function seedRequirements(): void {
  const existing = requirementRepo.listByProject(AUT_PROJECT_ID);
  if (existing.length > 0) {
    Log.for('seed').info(`AUT requirements already seeded (${existing.length} found), skipping.`);
    return;
  }
  for (const req of requirements) {
    requirementRepo.save(req);
  }
  Log.for('seed').info(`Seeded ${requirements.length} AUT requirements.`);
}
