export type RecorderMode = 'ui' | 'api' | 'element' | 'all';

/**
 * Playwright-native selector string generated by the official InjectedScript.
 * Format: "internal:role=button[name='Login'][i]" or "internal:label='Submit'"
 * This is the same format used by `playwright codegen` internally.
 */
export type PlaywrightSelector = string;

/**
 * A locator for a DOM element, expressed in terms Playwright can use directly.
 * - `official`: generated by Playwright's InjectedScript.generateSelectorSimple (preferred)
 * - `css`: minimal CSS fallback when the official engine fails
 */
export type LocatorRef =
  | { kind: 'official'; selector: PlaywrightSelector }
  | { kind: 'css'; selector: string };

export type PlaywrightActionName = 
  | 'click' | 'dblclick' | 'rightClick' | 'fill' | 'press' | 'check' | 'uncheck' 
  | 'selectOption' | 'setInputFiles' | 'hover' | 'dragTo' | 'goto'
  | 'recordElement';

export type RecorderEvent = {
  action: PlaywrightActionName;
  locator?: LocatorRef;
  secondaryLocator?: LocatorRef;
  value?: string;
  pageUrl: string;
  timestamp: number;
  metadata?: Record<string, unknown>;
};

export type RecorderStepPayload = {
  action: string;
  locator: LocatorRef;
  locatorCandidates: LocatorRef[];
  secondaryLocator?: LocatorRef;
  value?: string;
  pageUrl: string;
  timestamp: number;
  metadata?: Record<string, unknown>;
};

export type RecorderState = {
  isPaused: boolean;
  started: boolean;
  mode: RecorderMode;
  action?: 'START' | 'STOP' | 'PAUSE';
};