import React from 'react';

interface NlCasesPageProps {
  currentProjectId: string | null;
}

export function NlCasesPage({ currentProjectId }: NlCasesPageProps) {
  return (
    <div className="p-6">
      <h1 className="text-xl font-semibold mb-4">NL Test Cases</h1>
      <p className="text-gray-500">Natural language test cases generated by the AI pipeline will appear here.</p>
    </div>
  );
}