import { GoogleGenAI } from "@google/genai";
import { Project, TestStep, UIElement } from '@/shared/types';

const getAiClient = () => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    console.warn("API_KEY not found in environment.");
    return null;
  }
  return new GoogleGenAI({ apiKey });
};

export const generateStepsFromDescription = async (
  description: string,
  project: Project
): Promise<TestStep[]> => {
  const ai = getAiClient();
  if (!ai) return [];

  const elementsContext = project.pages.map(p => 
    `Page: ${p.name}\nElements: ${p.elements.map(e => `- ${e.name} (${e.selectorType}: ${e.value})`).join(', ')}`
  ).join('\n\n');

  const prompt = `
    You are a test automation engineer.
    Based on the available UI elements in the repository below, generate a list of test steps for the following test case description.
    
    Test Case Description: "${description}"
    
    Available Elements Repository:
    ${elementsContext}
    
    Output Format: JSON Array of objects with fields: action (OPEN, CLICK, TYPE, HOVER, SCROLL_TO, SELECT_OPTION, CHECK, UNCHECK, DRAG_AND_DROP, UPLOAD_FILE, ASSERT_VISIBLE, ASSERT_HIDDEN, ASSERT_TEXT, ASSERT_VALUE, EXTRACT_VAR, EVALUATE_JS, PRESS_KEY, WAIT), target (PageName.ElementName), data (optional value).
    Return ONLY the JSON array.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: prompt,
      config: {
        responseMimeType: 'application/json'
      }
    });

    const text = response.text;
    if (!text) return [];
    
    const rawSteps = JSON.parse(text);
    return rawSteps.map((s: any, idx: number) => ({
      id: `gen-${Date.now()}-${idx}`,
      action: s.action,
      target: s.target,
      data: s.data || '',
      description: 'Generated by AI'
    }));
  } catch (error) {
    console.error("AI Generation Failed:", error);
    return [];
  }
};

export const suggestSelector = async (htmlSnippet: string): Promise<Partial<UIElement>> => {
    const ai = getAiClient();
    if (!ai) return { selectorType: 'CSS', value: '' };

    const prompt = `
      Analyze this HTML snippet and suggest the best robust Playwright selector.
      Prioritize getByRole, getByTestId, then unique CSS/Text.
      
      HTML:
      ${htmlSnippet}
      
      Output JSON with keys: "selectorType" (one of: CSS, XPath, getByRole, getByText, getByTestId, getByLabel, getByPlaceholder), "value", "name" (suggested element name).
    `;

    try {
      const response = await ai.models.generateContent({
        model: 'gemini-3-flash-preview',
        contents: prompt,
        config: { responseMimeType: 'application/json' }
      });
      
      return JSON.parse(response.text || '{}');
    } catch (e) {
      console.error(e);
      return { selectorType: 'CSS', value: '' };
    }
}
